OPEN-ENT-NG/form

src/main/resources/i18n/fr.json, src/main/resources/public/sass/global/_formulaire.scss, src/main/resources/public/template/components/toaster.html, src/main/resources/public/template/lightbox/form-check-remind.html, src/main/resources/public/ts/controllers/form-editor.ts, src/main/resources/public/ts/controllers/forms-list.ts, src/main/resources/public/ts/services/DistributionService.ts, src/main/resources/public/ts/services/FormService.ts
Ajout d'une étape (suivi) avant d'envoyer un mail de rappel aux personnes n'ayant pas répondu au formulaire.
Le suivi contient un filtre afin de voir toutes les personnes, les personnes ayant répondu ou pas.
=> For 187 add step remind 

src/main/resources/public/ts/controllers/respond-question.ts, src/main/resources/public/ts/directives/formulaire-picker-file.ts
le bug sur les questions de type fichier qui gardé en mémoire le fichier de la question précédente est corrigé.
=> For 228 fix bug response on type files 

src/main/resources/i18n/fr.json, src/main/resources/public/template/lightbox/form-check-remind.html, src/main/resources/public/ts/controllers/forms-list.ts, src/main/resources/public/ts/controllers/forms-responses.ts
Les oublis du ticket ont été rajouté
=> fix():[FOR-187]fix add step remind

src/main/resources/public/template/containers/recap-questions.html
j'ai supprimé le non répondu ainsi que le lien modifier pour le type de question : zone de texte
=> For 250 fix textzone

src/main/java/fr/openent/formulaire/controllers/FormController.java
fix du bug de la duplication de questions
=> fix():[FOR-243]fix question's duplication

src/main/resources/public/template/containers/edit-form.html, src/main/resources/public/template/containers/prop-form.html, src/main/resources/public/template/containers/respond-question.html, src/main/resources/public/ts/controllers/respond-question.ts, src/main/resources/public/ts/directives/question/question-title.ts, src/main/resources/view-src/formulaire.html
Pour ce ticket j'ai eu un soucis avec le bouton suivant (fonction next) car le reset-guard attends une promise ce qui est le cas de next mais le soucis de next est qu'elle possède un await qui ne permet pas de faire fonctionner le reset-guard direct. C'est pour ça que j'ai créer 3 fonctions supplémentaires pour le côté réponse : nextGuard, prevGuard et saveAndQuitGuard.
=> FOR 198 page's alert 

src/main/resources/public/sass/global/components/_dominos.scss, src/main/resources/public/sass/global/components/_folder.scss, src/main/resources/public/template/containers/folders.html
fix of css and feat responsive view
=> For 231 responsive view

src/main/java/fr/openent/formulaire/export/FormResponsesExportPDF.java, src/main/resources/public/template/containers/results-form.html, src/main/resources/public/ts/controllers/form-results.ts, src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer-radio.ts
add  singleradio in result form
=> For 197 add singleradio for result form

src/main/resources/public/ts/controllers/form-prop.ts, src/main/resources/public/ts/models/Form.ts
change values of the rgpd's combobox and it default value
=> fix():[FOR-269]Rgpd's value change

src/main/resources/public/template/containers/prop-form.html
=> For 266 add cursor pointer

src/main/resources/public/template/containers/prop-form.html, src/main/resources/public/ts/directives/rgpd.ts, src/main/resources/sql/012-update-delegate-columns.sql
hand in delegate's information to null
=> fix():[FOR-268]hand in delegate's information to null

src/main/resources/public/ts/controllers/form-prop.ts
Le problème d'enregistrement de la date de fermeture est réglé.
=> For 263 save date_ending

src/main/resources/public/ts/services/FormService.ts
Le problème de l'enregistrement des propriétés est réglé.
=> For 271 save properties

src/main/resources/public/template/containers/folders.html, src/main/resources/public/template/containers/forms-list.html, src/main/resources/public/ts/app.ts, src/main/resources/public/ts/controllers/forms-list.ts, src/main/resources/public/ts/directives/index.ts, src/main/resources/public/ts/directives/lvl-drag-drop.ts, src/main/resources/public/ts/modules/index.ts, src/main/resources/public/ts/modules/lvl.ts
drag & drop fonctionnel (manque l'arborescence)
=> feat():[FOR-220]Drag & Drop

src/main/java/fr/openent/formulaire/controllers/FormController.java, src/main/resources/public/ts/controllers/forms-list.ts
le problème des duplications multiples est réglé.
=> For 261 multiple duplicate forms

src/main/resources/public/img/question_type/singleanswer_radio.svg, src/main/resources/public/sass/global/components/_new-question.scss
=> fix():[FOR-197]fix icon and pop-up

src/main/resources/public/sass/global/components/_icon.scss, src/main/resources/public/ts/models/Folder.ts
le problème de l'arborescence est fixé.
=> fix():[FOR-220]sort arborescence

src/main/resources/public/sass/global/_formulaire.scss, src/main/resources/public/sass/global/components/_folder.scss, src/main/resources/public/sass/global/components/_icon.scss
les vues mobile, tablette et laptop sont faites.
=> feat():[FOR-231]responsive view

src/main/java/fr/openent/formulaire/controllers/QuestionChoiceController.java, src/main/java/fr/openent/formulaire/service/QuestionChoiceService.java, src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionChoiceService.java, src/main/resources/public/ts/controllers/form-results.ts, src/main/resources/public/ts/services/QuestionChoiceService.ts
optimisation de l'export PDF sur les choix de question
=> feat():[FOR-265]optimise export PDF

src/main/resources/public/ts/directives/question/question-type/question-type-multipleanswer.ts, src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer-radio.ts, src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer.ts
rajout input-guard dans la modification des choix.
=> feat():[FOR-198]pages' alert change

src/main/resources/i18n/fr.json
j'ai supprimé l'occurrence demandé dans les exemples RGPD.
=> For 273 delete occurence of example 

src/main/resources/public/ts/controllers/form-editor.ts
Suppression des espaces insécables via le replace
=> For 281 delete space insecable 

src/main/resources/public/ts/controllers/form-results.ts, src/main/resources/public/ts/models/QuestionChoice.ts
création d'une fonction pour retirer les espaces insécables pour l'export de PDF
=> For 281 delete space insecable in export PDF

src/main/resources/i18n/fr.json
le titre pour le radio bouton est modifié
=> For 197 radio button's name change

src/main/resources/public/sass/global/_formulaire.scss, src/main/resources/public/template/containers/forms-list.html
fix du css pour les checkbox de la liste des forms
=> fix():[FOR-284]fix select all forms

src/main/resources/public/ts/controllers/forms-list.ts
block sharing of forms without question' title
=> For 297 block sharing of forms without question' title

src/main/resources/public/template/containers/edit-form.html, src/main/resources/public/ts/controllers/form-editor.ts, src/main/resources/public/ts/directives/question/question-title.ts, src/main/resources/public/ts/directives/question/section-item.ts, src/main/resources/sql/014-add-conditional-questions.sql
=> fix():[FOR-308]fix pop up alert add question

src/main/resources/public/ts/directives/question/question-item.ts, src/main/resources/public/ts/directives/question/section-item.ts
fix pop up alert on question and section change
=> fix():[FOR-292]fix pop up alert on question and section change

src/main/resources/public/sass/global/components/_edit-form.scss, src/main/resources/public/ts/directives/question/section-item.ts
fix css button dontSave section
=> fix():[FOR-304]fix css button dontSave section

src/main/resources/public/ts/directives/question/question-type.ts, src/main/resources/public/ts/directives/question/section-item.ts
delete trigger pop up alert for question choices and conditionnal questions
=> fix():[FOR-308]delete trigger pop up alert for question choices 

src/main/resources/public/ts/controllers/respond-question.ts
scrollToTop on previous and next button
=> fix():[FOR-321]scrollToTop

src/main/resources/i18n/fr.json, src/main/resources/public/ts/controllers/forms-list.ts
=> fix():[FOR-297]Block sharing form

src/main/resources/public/template/containers/forms-responses.html
Delete first checkbox in responses' view
=> feat():[FOR-324]Delete first checkbox in responses' view

src/main/resources/public/template/containers/prop-form.html, src/main/resources/public/ts/controllers/form-editor.ts
fix save button and update date + fix space in prop form
=> fix():[FOR-320]fix save button and update date

src/main/resources/i18n/fr.json, src/main/resources/public/ts/controllers/form-editor.ts, src/main/resources/public/ts/controllers/forms-list.ts, src/main/resources/public/ts/directives/question/section-item.ts, src/main/resources/public/ts/utils/formElement.ts
block share and save if multiple conditional in question
=> feat():[FOR-310]block share and save if multiple conditional in question

src/main/resources/public/ts/controllers/form-editor.ts, src/main/resources/public/ts/directives/question/question-item.ts, src/main/resources/public/ts/directives/question/question-type/question-type-multipleanswer.ts, src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer-radio.ts, src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer.ts, src/main/resources/public/ts/directives/question/section-item.ts
=> fix():[FOR-292]fix input-guard

src/main/java/fr/openent/formulaire/controllers/FormController.java, src/main/java/fr/openent/formulaire/export/FormResponsesExportPDF.java
=> feat():[FOR-326]new export pdf

.github/workflows/dev-check-repository.yml, .gitignore, build.gradle, build.sh, gradle.properties, jest.config.js, package.json, src/main/java/fr/openent/formulaire/export/FormResponsesExportCSV.java, src/main/java/fr/openent/formulaire/export/FormResponsesExportPDF.java, src/main/resources/public/ts/models/__mocks__/entcore.ts, src/main/resources/public/ts/services/QuestionTypeService.ts, src/main/resources/public/ts/services/__tests__/questiontypeservice.test.ts, src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java, tsconfig.json
install of unit test on Formulaire
=> feat():[FOR]TestUnit

src/main/resources/i18n/fr.json, src/main/resources/public/ts/directives/question/result-question-item.ts
- Fix spellings
- Delete useless imports
- Change choice of word for results of multipleanswer questions
https://entsupport.gdapublic.fr/browse/FOR-359
=> fix(): [FOR-359] Fix and change some words

src/main/resources/public/ts/behaviours.ts
- Change form link get from linker according to new routes formats
https://entsupport.gdapublic.fr/browse/FOR-357
=> fix(): [FOR-357] Fix linker form link

src/main/resources/public/sass/panda/_formulaire.scss
- Make input background transparent for section title in 1D theme
=> fix(): [FOR-360] Fix input background for section title

README.md
ajout d'une description technique 
merge après vérification de PO.
=> docs: #CO-1650 add technical description

formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/template/lightbox/form-sharing.html
Usually a form can be shared to allow other people to contrib or respond to it for example.
A public form is shared for respond thanks to a public link. But the sharing system to contrib was missing so we add it here.
FOR-411 : https://entsupport.gdapublic.fr/browse/FOR-411
=> fix() : [FOR-411] Allow sharing system for a public form

formulaire/src/main/resources/public/ts/controllers/forms-list.ts
For public forms, we want all the people to respond as anonymous so we don't want to share them the form as responder with share system. They will be forced to use the public link insted.
FOr-411 : https://jira.support-ent.fr/browse/FOR-411
=> fix(sharePanel): [FOR-411] Hide response column in sharePanel for public forms

formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
Add a missing return in a condition leading to the end of the function. Allows to fix a bug on delete forms shared for management.
FOR-407 : https://jira.support-ent.fr/browse/FOR-407
=> fix: [FOR-407] Fix deletion of forms shared in gestion

formulaire/src/main/resources/public/sass/global/_formulaire.scss, formulaire/src/main/resources/public/template/lightbox/form-sharing.html
Ellipses the public-link when it's too long for the lightbox.
FOR-420 : https://jira.support-ent.fr/browse/FOR-420
=> fix: [FOR-420] Deals with public link too long

formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts
Fix public responses when answer is null.
FOR-423: https://jira.support-ent.fr/browse/FOR-423
=> fix: [FOR-423] Fix public responses when answer is null

formulaire-public/src/main/java/fr/openent/formulaire_public/controllers/FormulairePublicController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormulaireController.java
We add an API endpoint to access the config of the module.
This route is only allowed for admins.
Logins and passwords are replaced by '*'.
Issue-74 : https://github.com/OPEN-ENT-NG/form/issues/74
=> feat(config): [Issue-74] Add routing to get config safely

formulaire/src/main/resources/public/sass/global/components/_dominos.scss
Fix image height on form dominos.
FOR-419 : https://jira.support-ent.fr/browse/FOR-419
=> fix(img): [FOR-419] fix image size on dominos

common/src/main/java/fr/openent/form/core/constants/Fields.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/resources/public/ts/controllers/forms-list.ts
Reprise de la PR #69
Even with the column hidden it was reappearing when adding user for sharing.
So we changed the logic : now we modify directly the response of the API endpoint giving the diferent sharing rights possible so the directive sharePanel is built according to the rights we really need.
FOR-411 : https://jira.support-ent.fr/browse/FOR-411
=> fix(sharePanel): [FOR-411] remove column in sharePanel for public forms

build.sh, gulpfile.js
Change module argument to work properly with new node version.
More explanation [here](https://github.com/OPEN-ENT-NG/presences/pull/170).
Relancer la commande node pour faire un gulp build, ne devrait plus générer l'erreur
Issue 78 : https://github.com/OPEN-ENT-NG/form/issues/78
=> chore(node): [Issue-78] change args to specify targeted module

common/src/main/resources/ts/utils/formElement.ts, formulaire/src/main/resources/public/template/lightbox/questions-reorganization.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
On using questions reorganization pop up, we observed some issues (position, logic in arrows displaying, ...).
It highlighted index mistakes in functions calculating new question positions.
FOR-372 : https://jira.support-ent.fr/browse/FOR-372
=> fix(organization): [FOR-372] fix index issues with questions reorganization

common/src/main/resources/ts/services/FormService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/service/FormService.java, formulaire/src/main/java/fr/openent/formulaire/service/RelFormFolderService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultRelFormFolderService.java, formulaire/src/main/resources/public/ts/controllers/forms-list.ts, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFormServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultRelFormFolderServiceTest.java
When we restore a form shared to someone, it's restored for the person who restored it but not for the other ones.
A new API endpoint was created specically for it.
FOR-424 : https://jira.support-ent.fr/browse/FOR-424
=> fix(restore): [FOR-424] fix restoration for shared forms

formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java
A field used was not a good one, it has been changed to the good one.
FOR-430 : https://jira.support-ent.fr/browse/FOR-430
=> fix(fields): [FOR-430] fix error in field syntax

common/src/main/java/fr/openent/form/core/constants/Fields.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultNeoService.java
A field used was not a good one, it has been changed to the good one.
FOR-429 : https://jira.support-ent.fr/browse/FOR-429
=> fix(fields): [FOR-429] fix error in field syntax

formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java, formulaire/src/main/java/fr/openent/formulaire/security/ShareAndOwner.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultDistributionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFolderService.java
A field used was not a good one, it has been changed to the good one.
Some useless code was removed.
FOR-432 : https://jira.support-ent.fr/browse/FOR-432
=> fix(fields): [FOR-432] fix error in field syntax

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/resources/ts/models/FormElement/Question.ts, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-shortanswer.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts, formulaire/src/main/resources/sql/016-update-question.sql, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java
Make placeholder editable for short answer
Create a formulaire, and add short question : now you can also update placeholder and choose what you want to display.
After, check in preview, and response if you see what you wrote.
[FOR-257] https://jira.support-ent.fr/browse/FOR-257
=> FOR-257 make placeholder editable for short answer

formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts
Update placeholder in formulaire-public
Add a formulaire-public and check to answer : placeholder should the same as you defined in creation
[FOR-257] https://jira.support-ent.fr/browse/FOR-257
=> feat(question): #FOR-257 update placeholder for formulaire-public

formulaire/src/main/resources/public/sass/global/components/_edit-form.scss
Add just a little bit of responsive for new question type matrix.
FOR-435 : https://jira.support-ent.fr/browse/FOR-435
=> feat(matrix) : [FOR-435] a bit of responsive for matrix title

formulaire/src/main/resources/public/sass/global/_formulaire.scss, formulaire/src/main/resources/public/sass/global/components/_edit-form.scss, formulaire/src/main/resources/public/template/containers/edit-form.html
Fix header to scroll in edit form view
Create a form with several question ; go to edit view and scroll : title & btn a the top of the page should stay visible when you scroll to bottom
[FOR-259] https://jira.support-ent.fr/browse/FOR-259
=> feat(edit-form): #FOR-259 fix header to scroll

formulaire/src/main/resources/public/sass/global/components/_edit-form.scss
Add z-index to fix issue with "editor"
=> feat(edit-form): #FOR-259 fix z-index issue with editor

common/src/main/java/fr/openent/form/core/constants/Constants.java, common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/enums/ChoiceTypes.java, common/src/main/java/fr/openent/form/core/enums/Events.java, common/src/main/java/fr/openent/form/core/enums/QuestionTypes.java, common/src/main/resources/ts/core/constants/constants.ts, common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/utils/graph.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormulaireController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionChoiceController.java, formulaire/src/main/java/fr/openent/formulaire/export/FormResponsesExportCSV.java, formulaire/src/main/java/fr/openent/formulaire/export/FormResponsesExportPDF.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormElementService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultResponseService.java, formulaire/src/main/resources/public/sass/global/components/_result-form.scss, formulaire/src/main/resources/public/template/containers/results-form.html, formulaire/src/main/resources/public/ts/controllers/form-results.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts, formulaire/src/main/resources/public/ts/directives/question/result-question-item.ts, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java
Last part of the matrix evolution : 
- display responses in a graph
- export responses into a PDF file with in a similar graph
- export responses into a CSV file
FOR-438 : https://jira.support-ent.fr/browse/FOR-438
=> feat(matrix) : [FOR-438] results, exports pdf and csv of a matrix

formulaire/src/main/resources/public/sass/global/components/_respond-question.scss
Harmonize width columns for matrix response table
FOR-447 : https://jira.support-ent.fr/browse/FOR-447
=> fix(matrix) : [FOR-447] improve display table for matrix

common/src/main/resources/ts/core/constants/constants.ts, common/src/main/resources/ts/utils/color.ts, common/src/main/resources/ts/utils/graph.ts, common/src/main/resources/ts/utils/utils.ts, formulaire/src/main/resources/public/ts/directives/question/result-question-item.ts
Use new color system for graph generation
FOR-443 : https://jira.support-ent.fr/browse/FOR-443
=> feat(colors) : [FOR-443] improve graph colors system

common/src/main/resources/ts/core/enums/prop-position.ts, common/src/main/resources/ts/models/Form.ts, common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/models/QuestionChoice.ts, common/src/main/resources/ts/utils/formElement.ts, common/src/main/resources/ts/utils/public.ts, formulaire-public/src/main/resources/public/ts/controllers/recap.ts, formulaire-public/src/main/resources/public/ts/directives/public-matrix.ts, formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts, formulaire-public/src/main/resources/public/ts/directives/public-recap-question-item.ts, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionChoiceService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/main/resources/public/sass/global/components/_edit-form.scss, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-matrix.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-multipleanswer.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer-radio.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer.ts, formulaire/src/main/resources/public/ts/directives/question/recap-question-item.ts, formulaire/src/main/resources/public/ts/directives/question/respond-matrix.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts, formulaire/src/main/resources/sql/016-matrix.sql, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java
Add positionning and reordering system for children question of matrix and all question choices
For-262 : https://jira.support-ent.fr/browse/FOR-262
=> feat(choices) : [FOR-262] add positioning for choices and matrix children

formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java
Improve SQL request to get questions for exports. Makes it easier to index their positions in CSV export.
FOR-448 : https://jira.support-ent.fr/browse/FOR-448
=> feat(export) : [FOR-448] fix question indexes in CSV export

common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/models/QuestionChoice.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-matrix.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-multipleanswer.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer-radio.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer.ts
Recalculate choices positions on delete choice to avoid wrong position.
Sort choices by position on sync or other needed moments.
FOR-449 : https://jira.support-ent.fr/browse/FOR-449
=> fix(position) : [FOR-449] fix and improve calculation of choices position

formulaire/src/main/resources/public/sass/global/components/_edit-form.scss, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-matrix.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-multipleanswer.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer-radio.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer.ts
Improve input lengths of choices in form-editor page
FOR-440 : https://jira.support-ent.fr/browse/FOR-440
=> style(choices) : [FOR-440] improve input lengths of choices

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/enums/ChoiceTypes.java, common/src/main/java/fr/openent/form/core/model/Model.java, common/src/main/java/fr/openent/form/core/model/Question.java, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
To facilitate access to objects and optimize their use, we create models.
Our model question contain all question objects.
https://github.com/OPEN-ENT-NG/form/issues/106
=> feat(form): #106 add a model named question

common/src/main/resources/ts/utils/graph.ts, formulaire/src/main/resources/public/ts/controllers/form-results.ts
Add percentage in PDF's graph for multiple choices question
Create a form with multiple choice question, export result in PDF and check if percentage are present in bar's chart
[FOR-361] https://jira.support-ent.fr/browse/FOR-361
=> feat(PDF): #FOR-361 add percentage in PDF's graph

common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/utils/graph.ts
- Matrix results were not displayed anymore because we checked results corresponding to the matrix id instead of checking the results corresponding to to matrix's children ids (a result respond to a line/child, not to the whole matrix).
- Change name of a variable for better understanding.
FOR-461 : https://jira.support-ent.fr/browse/FOR-461
=> fix(matrix) : [FOR-461] fix display results for matrix

common/src/main/java/fr/openent/form/core/constants/Constants.java, common/src/main/java/fr/openent/form/core/enums/QuestionTypes.java, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
Allow response to freetext questions
FOR-460 : https://jira.support-ent.fr/browse/FOR-460
=> fix(response) : [FOR-460] allow response to freetext questions

.gitignore, formulaire/src/main/resources/public/sass/global/_formulaire.scss, formulaire/src/main/resources/public/sass/global/components/_icon.scss, gulpfile.js
Change the name of MDI icons font-family to avoid mixing with other modules.
FOR-459 : https://jira.support-ent.fr/browse/FOR-459
=> feat(icons) : [FOR-459] make MDI icons use specific to Formulaire

formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-matrix.ts
The wrong prop was target for reorderring lines of a matrix.
FOR-465 : https://jira.support-ent.fr/browse/FOR-465
=> fix(position) : [FOR-465] fix ordering for lines of a matrix

common/src/main/java/fr/openent/form/core/constants/Constants.java, common/src/main/java/fr/openent/form/core/constants/Fields.java, formulaire-public/src/main/java/fr/openent/formulaire_public/controllers/FormulairePublicController.java, formulaire-public/src/main/java/fr/openent/formulaire_public/service/impl/DefaultResponseService.java, formulaire-public/src/main/resources/public/ts/behaviours.ts, formulaire/src/main/java/fr/openent/formulaire/Formulaire.java, formulaire/src/main/java/fr/openent/formulaire/helpers/FutureHelper.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultDistributionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultSectionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/FormulaireRepositoryEvents.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/ImportExportService.java, formulaire/src/main/resources/sql/017-add-original-form-id.sql
Implement functions for import and export via Archive module :
- Add a SQL field named "original_form_id" containing the id of the form we copy
- Change all the "BEGIN;" and "COMMIT;" messages in transactions by a constants containing these values
- Implement the functions of import and export called by the Archive module
-> Needs to add i18n in entcore : cf https://github.com/opendigitaleducation/entcore/pull/298
I also wrote a documentation about this export/import system with the Archive module : https://confluence.support-ent.fr/pages/viewpage.action?pageId=127632788
FOR-355 : https://jira.support-ent.fr/browse/FOR-355
- [] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
=> feat(import/export) : [FOR-355] add export/import event functions for Archive module

formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionSpecificFieldService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionSpecificFieldService.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionSpecificServiceTest.java
Add new SQL table to manage specific question's field
https://confluence.support-ent.fr/pages/viewpage.action?pageId=67210096
Create new question or session, and try to add different question type like cursor or other to check possible regression
[FOR-466] https://jira.support-ent.fr/browse/FOR-466
=> * feat(question-specific-field): #FOR-466 Add new SQL table to manage question's specific field

formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java
Add condition to exclude id when add specific field column
[FOR-468] https://jira.support-ent.fr/browse/FOR-468
=> fix(question-type-cursor): #FOR-468 add condition to fix sql data issue

common/src/main/resources/ts/models/Response.ts, common/src/main/resources/ts/services/ResponseService.ts, common/src/main/resources/ts/utils/public.ts, formulaire-public/src/main/resources/public/template/containers/recap.html, formulaire-public/src/main/resources/public/template/containers/respond-question.html, formulaire-public/src/main/resources/public/ts/controllers/recap.ts, formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts, formulaire-public/src/main/resources/public/ts/directives/public-recap-question-item.ts
First part of the refactoring of the response system.
It only impacts response system in formulaire-public and doesn't include MATRIX type questions (will be in next PR).
=> refactor(response) : [FOR-454] refacto response system in formulaire-public (without MATRIX)

common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/utils/public.ts, formulaire-public/src/main/resources/public/template/containers/respond-question.html, formulaire-public/src/main/resources/public/ts/controllers/captcha.ts, formulaire-public/src/main/resources/public/ts/controllers/recap.ts, formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire-public/src/main/resources/public/ts/directives/public-matrix.ts, formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts
Second part of the refactoring of the response system.
It only impacts response system in formulaire-public.
This PR is following the #121 (same but without matrix management)
=> refactor(response) : [FOR-454] refacto response system in formulaire-public (with MATRIX)

common/src/main/resources/ts/models/FormElement/Question.ts, formulaire-public/src/main/resources/public/ts/directives/public-matrix.ts, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultResponseService.java, formulaire/src/main/resources/public/template/containers/respond-question.html, formulaire/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/directives/question/respond-matrix.ts
Fourth part of the refactoring of the response system.
It only impacts response system in formulaire classic (plus a fix in formulaire-public)
This PR is following : 
- #121 --> formulaire-public without matrix 
- #123 --> formulaire-public with matrix
- #124 --> formulaire classic without matrix
=> refactor(response) : [FOR-454] refacto response system in formulaire classic (with MATRIX)

formulaire/src/main/java/fr/openent/formulaire/service/impl/ImportExportService.java, formulaire/src/main/resources/public/ts/controllers/forms-list.ts
On import form, we now refresh current folder if it's the root folder.
And the placeholder of short answer is now imported correctly.
https://jira.support-ent.fr/browse/FOR-385
=> fix(import) : [FOR-385] fix placeholder data for short answer and refresh current folder

common/src/main/resources/ts/models/FormElement/Question.ts, formulaire-public/src/main/resources/public/ts/controllers/recap.ts, formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts, formulaire/src/main/resources/public/template/containers/preview-form.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/directives/question/respond-matrix.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts
Last part of the refactoring of the response system.
It only impacts response system in formulaire classic (plus a fix in formulaire-public)
This PR is following :
- #121 --> formulaire-public without matrix 
- #123 --> formulaire-public with matrix
- #124 --> formulaire classic without matrix
- #125 --> formulaire classic with matrix
=> refactor(response) : [FOR-454] refacto response system in formulaire preview

common/src/main/resources/ts/utils/graph.ts
Truncate percentage to 2 digits in PDF export
https://jira.support-ent.fr/browse/FOR-473
=> fix(pdf) : [FOR-473] truncate percentage to 2 digits in PDF export

common/src/main/java/fr/openent/form/core/constants/DistributionStatus.java, common/src/main/resources/ts/core/enums/formulaire-filters.ts, common/src/main/resources/ts/models/Distribution.ts, common/src/main/resources/ts/models/Form.ts, formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/ts/controllers/forms-responses.ts
The IN_PROGRESS distribution status was created at the beginning of the module but never really used.
This commit clean the code of this unused status.
FOR-481 : https://jira.support-ent.fr/browse/FOR-481
=> fix(filters) : [FOR-481] remove IN_PROGRESS status (unused)

common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/models/Response.ts, common/src/main/resources/ts/services/ResponseService.ts, common/src/main/resources/ts/utils/public.ts, formulaire-public/src/main/resources/public/template/containers/recap.html, formulaire-public/src/main/resources/public/template/containers/respond-question.html, formulaire-public/src/main/resources/public/ts/controllers/captcha.ts, formulaire-public/src/main/resources/public/ts/controllers/recap.ts, formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire-public/src/main/resources/public/ts/directives/public-matrix.ts, formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts, formulaire-public/src/main/resources/public/ts/directives/public-recap-question-item.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java, formulaire/src/main/java/fr/openent/formulaire/security/CustomShareAndOwner.java, formulaire/src/main/java/fr/openent/formulaire/service/ResponseService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultResponseService.java, formulaire/src/main/resources/public/template/containers/preview-form.html, formulaire/src/main/resources/public/template/containers/respond-question.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/directives/question/respond-matrix.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts, formulaire/src/main/resources/sql/019-update-current-sharing.sql
This PR includes all the following PR :
- #121 --> formulaire-public without matrix 
- #123 --> formulaire-public with matrix
- #124 --> formulaire classic without matrix
- #125 --> formulaire classic with matrix
- #127 --> formulaire classic preview
=> refator(response) : [FOR-454] refacto response system

formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts
Add default placeholder for shortanswer when custom one has no value.
FOR-476 : https://jira.support-ent.fr/browse/FOR-476
=> fix(shortanswer): [FOR-476] add default placeholder for shortanswer

common/src/main/java/fr/openent/form/helpers/UtilsHelper.java, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionSpecificFieldService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionSpecificFieldService.java, formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/sass/global/components/containers/cursor/_question-type-cursor.scss, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor.ts, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionSpecificServiceTest.java
- Allow update of modifications
- Avoid wrong values for min, max and step
- Change some CSS
- update a value, save, refresh the page and see wich value is display (should be the new one)
- min greater than max
- max smaller than min
- min and max equal
- difference between min and max smaller than step
FOR-456: https://jira.support-ent.fr/browse/FOR-456
=> fix(cursor): [FOR-456] fix value management and saving for cursor questions

formulaire/src/main/resources/public/ts/controllers/form-results.ts
Calcul of percentage was including distribution of people who didn't go through question (in conditionnal case).
Now we filter the distributions before calculating.
FOr-474 : https://jira.support-ent.fr/browse/FOR-474
=> fix(result): [FOR-474] fix percentage in multipleanswer result graph

common/src/main/java/fr/openent/form/core/constants/Constants.java, common/src/main/java/fr/openent/form/core/constants/Tables.java, common/src/main/java/fr/openent/form/core/enums/QuestionTypes.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionSpecificFieldService.java, formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/sass/global/components/containers/cursor/_question-type-cursor.scss, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionSpecificServiceTest.java
- fix text errors in a file of constants in back
- design creation side and response side are improved
- value initialisation in response side is fixed
- duplication of a form now includes questions with specifics fields (like cursor type)
FOR-457 : https://jira.support-ent.fr/browse/FOR-457
=> fix(cursor): [FOR-457] fix design and value initialisation

formulaire/src/main/resources/public/sass/global/components/containers/cursor/_question-type-cursor.scss, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts
Redesign input cursor :
- a pin cursor with the selected value follows the native cursor
- a colored progress bar follows this same native cursor
- responsive
- works on every browser
FOR-462 : https://jira.support-ent.fr/browse/FOR-462
=> feat(cursor): [FOR-462] custom CSS for cursor questions

formulaire/src/main/resources/public/ts/directives/question/question-title.ts
Hide a feature that will be used (and useful) only in next version.
FOR-486 : https://jira.support-ent.fr/browse/FOR-486
=> fix(matrix) : [#FOR-486] hide matrix selection (feat for next version)

formulaire/src/main/resources/public/sass/panda/_formulaire.scss
Next changes on 1D panda theme have been made :
- fix header to the top
- on creation side : label cursor have more space
- on response side : progress bar cursor is realigned with native pin
FOR-485 : https://jira.support-ent.fr/browse/FOR-485
=> fix(css) : [#FOR-485] fix CSS for 1D panda theme

common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/utils/graph.ts, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/ts/controllers/form-results.ts, formulaire/src/main/resources/public/ts/directives/question/result-question-item.ts
Create result view with an apexchart type area & export PDF
Create a form (or use an old one), add question type cursor ; share it and create two or more answers then go to result view and check if your graph is coherent, and average is okay. You also can try to export it in PDF.
[FOR-458] https://jira.support-ent.fr/browse/FOR-458
=> feat(question-type-cursor): #FOR-458 create result view with graph

formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultNotifyService.java
Add formId in params when calling notifyTimeline for use in mobile app
FOR-494 : https://jira.support-ent.fr/browse/FOR-494
=> feat(notify): [#FOR-494] add param for notify in mobile application

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
In edit-form view there is an auto saving onClick. It was triggered when using the text editor but now we avoid it.
FOR-490 : https://jira.support-ent.fr/browse/FOR-490
=> fix(editor): [#FOR-490] block auto saving when using the text editor in edit-form view

formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
Duplication was broken because of the retrieving of question_specifics informations wrongly joined, now it's working
FOR-491 : https://jira.support-ent.fr/browse/FOR-491
=> fix(duplication): [#FOR-491] fix duplication

common/src/main/java/fr/openent/form/core/constants/Fields.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultNotifyService.java
Change resource param in notify for mobile.
Simple ID has become an objet with ID and URI.
FOR-494: https://jira.support-ent.fr/browse/FOR-494
=> fix(notify): [#FOR-494] fix param for notify in mobile application

common/src/main/resources/ts/utils/graph.ts, formulaire/src/main/resources/public/ts/controllers/form-results.ts, formulaire/src/main/resources/public/ts/directives/question/result-question-item.ts
When you export PDF, response were not filtered, and we had all response insteed only question's responses. 
Create new form, add question's type cursor and share it. Add at least 3 responses to have significant result, and compare export PDF and result view. It's should be the same average and graph.
[FOR-483] https://jira.support-ent.fr/browse/FOR-483
=> fix(question-type-cursor): #FOR-483 fix wrong response for PDF

common/src/main/java/fr/openent/form/core/constants/Fields.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultNotifyService.java
Add param to mobile app
Try to click on notif timeline on mobile app side
[FOR-494] https://jira.support-ent.fr/browse/FOR-494
=> fix(mobile-app): #FOR-494 add param to mobile app

formulaire/src/main/resources/public/template/containers/preview-form.html
Fix preview for matrix in section : the wrong varaible was check hence the wrong directive was used.
FOR-507 : https://jira.support-ent.fr/browse/FOR-507
=> fix(preview) : [#FOR-507] fix preview for matrix in section

formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultDistributionService.java
Update date_response when response is modified to display the moment of the last modification.
FOR-511 : https://jira.support-ent.fr/browse/FOR-511
=> fix(response) : [#FOR-511] update date_response when response is modified

common/src/main/resources/ts/models/__mocks__/entcore.ts, formulaire/src/main/resources/public/ts/controllers/forms-list.ts, package.json
Update typescript version -> 4.8.3
[FOR-515](https://jira.support-ent.fr/browse/FOR-515)
=> feat(typescript): #FOR-515 update typescript version

common/src/main/resources/ts/models/FormElement/FormElement.ts, formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/question-item.ts
Add new rules to check if min and max values are consistent with step choice.
Create a question type cursor, choose min and max val of your choice and add a step. If it's not consistent (exemple if you choose min val = 0 & max val = 10, your step must be peer)
[FOR-504](https://jira.support-ent.fr/browse/FOR-504)
=> feat(question-type-cursor): #FOR-504 add rules for cursor's choices

formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json
Add hover to describe question type cursor
On the form of your choice, click to add a new question. Check if the hover of question type cursor have the right description.
[FOR-496](https://jira.support-ent.fr/browse/FOR-496)
=> feat(question-type-cursor): #FOR-496 add hover to describe question type cursor

common/src/main/resources/ts/models/Response.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts
Answer was type string, and input type range should be a type number
Add a new question type cursor and share it. Go te response view, and select an answer for each question. When you update, go back, or save it and check if cursor is still at the same place that the blue indicator.
[FOR-498](https://jira.support-ent.fr/browse/FOR-498)
=> fix(question-type-cursor): #FOR-498 fix input range error

common/src/main/resources/ts/utils/graph.ts
Show toolbar in apex chart, fix title (lang.translate missing) & remove useless import
[FOR-458](https://jira.support-ent.fr/browse/FOR-458)
=> fix(question-type-cursor): #FOR-458 fix some graph's parameters

common/src/main/resources/ts/models/Distribution.ts, common/src/main/resources/ts/services/DistributionService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/DistributionController.java, formulaire/src/main/java/fr/openent/formulaire/helpers/FutureHelper.java, formulaire/src/main/java/fr/openent/formulaire/service/DistributionService.java, formulaire/src/main/java/fr/openent/formulaire/service/FormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultDistributionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/main/resources/public/ts/controllers/main.ts
When a reminder is sent for a form, the link allowed to generate a new distribution every time, even if only one answer was authorized.
Checks were added to avoid this.
FOR-503 : https://jira.support-ent.fr/browse/FOR-503
=> fix(reminder) : [#FOR-503] avoid responder to respond several times when forbidden

formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/question-item.ts
Add default value if not filled
[FOR-504](https://jira.support-ent.fr/browse/FOR-504)
=> fix(question-type-cursor): #FOR-504 fix null value

formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/service/FormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFormServiceTest.java
- The SQL request to get the forms to display in the linker now includes the public forms.
- A corresponding test was added for this function.
- Switch from Handler to Future.
FOR-488 : https://jira.support-ent.fr/browse/FOR-488
=> fix(linker) : [#FOR-488] allows public forms to appear in the linker

formulaire/src/main/resources/sql/017-add-constraints.sql
We found some questions or sections with same position in forms during tests but it shouldn't be possible.
We added constraints to avoid that.
We also added constraints to be sure that the right colums or null or filled as it should be according to the situation.
FOR-508 : https://jira.support-ent.fr/browse/FOR-508
=> fix(sql) : [#FOR-508] add constraints in SQL for questions and sections

common/src/main/resources/ts/utils/graph.ts
Update graph's option : hide toolbar & disable zoom
[FOR-519](https://jira.support-ent.fr/browse/FOR-519)
=> fix(question-type-cursor): #FOR-519 hide toolbar & disable zoom

formulaire-public/src/main/java/fr/openent/formulaire_public/service/impl/DefaultNotifyService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultNotifyService.java
- add mobile notif for formulaire-public
- change mobile notif target link on response
- delete useless code
FOr-522 : https://jira.support-ent.fr/browse/FOR-522
=> fix(notification) : [#FOR-522] add mobile notif for formulaire-public

formulaire/src/main/resources/public/ts/directives/question/question-type.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor.ts
Added rules for disabled input is form has been shared, and someone already response
[FOR-518](https://jira.support-ent.fr/browse/FOR-518)
=> fix(question-type-cursor): #FOR-518 disable input if form has response

common/src/main/resources/ts/utils/graph.ts, formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/template/lightbox/form-check-remind.html
change i18n key
[FOR-526](https://jira.support-ent.fr/browse/FOR-526)
=> fix(question-type-cursor): #FOR-526 change i18n key

common/src/main/resources/ts/directives/rgpd.ts, formulaire-public/src/main/resources/public/template/containers/recap.html, formulaire-public/src/main/resources/public/template/containers/respond-question.html, formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts, formulaire-public/src/main/resources/public/ts/directives/public-recap-question-item.ts, formulaire/src/main/resources/public/template/containers/preview-form.html, formulaire/src/main/resources/public/template/containers/recap-questions.html, formulaire/src/main/resources/public/template/containers/respond-question.html, formulaire/src/main/resources/public/template/containers/results-form.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/controllers/form-results.ts, formulaire/src/main/resources/public/ts/controllers/recap-questions.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-freetext.ts, formulaire/src/main/resources/public/ts/directives/question/recap-question-item.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts, formulaire/src/main/resources/public/ts/directives/question/result-question-item.ts, formulaire/src/main/resources/public/ts/directives/question/section-item.ts
Multimedia content (videos) were impossible to save in ODE text-editor.
If saved they never displayed anything.
Now we can save them and read them as it should be.
- Added some variables' type
- Change code architecture of some directive
FOR-490 : https://jira.support-ent.fr/browse/FOR-490
=> fix(text-editor) : [#FOR-490] fix displaying of multimedia content from ODE text-editor

formulaire/src/main/resources/public/ts/controllers/forms-list.ts
When people are sharing a form they shouldn't have the right to respond by default so we uncheck it.
FOR-512 : https://jira.support-ent.fr/browse/FOR-512
=> fix(sharing): [#FOR-512] uncheck response right by default for owner

common/src/main/java/fr/openent/form/helpers/FutureHelper.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/FormulaireRepositoryEvents.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/ImportExportService.java
Add the new table question_specific_fields to the import/export data (used for cursor questions for example)
FOr-495 : https://jira.support-ent.fr/browse/FOR-495
=> fix(import/export): [#FOR-495] add question_specifics table to import/export data

formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
When sharing forms, in some misunderstood cases the distriutions are created but the boolean prop "sent" is not updated.
It creates cases where the form is shared but has a prop saying he's not.
In those cases it was impossible to send a reminder to people who has not yet responded to the form.
Now we check this wrong case when sending the reminder and update the "sent" prop correctly if needed at the same time.
Copie de la PR #180 closed parce que la branche target a été delete
FOR-487 : https://jira.support-ent.fr/browse/FOR-487
=> fix(reminder): [#FOR-487] fix form prop SENT when value is wrong

common/src/main/resources/ts/core/constants/date_formats.ts, common/src/main/resources/ts/core/constants/index.ts, common/src/main/resources/ts/services/FormService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/helpers/DataChecker.java
Adapt the front date formats to have right UTC times for BDD.
FOR-532 : https://jira.support-ent.fr/browse/FOR-532
=> fix(date): [#FOR-532] fix date_opening and date_ending formats

formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/main/resources/sql/017-add-constraints.sql, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java
Reset values to NULL before updating them for question position, section_position, ...
FOR-533 : https://jira.support-ent.fr/browse/FOR-533
=> fix(dragAndDrop): [#FOR-533] fix question dragAndDrop

formulaire/src/main/resources/public/ts/behaviours.ts
The link to respond to a public form is different from a classic form.
Now the link generated in the linker follows this difference.
FOR-488 : https://jira.support-ent.fr/browse/FOR-488
=> fix(linker) : [#FOR-488] fix link for public forms in the linker

formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts
Init cursor by default to minimum value for all view (response & preview)
You can create a form with at least one question cursor's type, and look at preview, then share it and go to response view : all input range should by init at minimum value.
[FOR-525](https://jira.support-ent.fr/browse/FOR-525)
=> feat(question-type-cursor): #FOR-525 init cursor response to minimum

formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
- fix matrix duplication
- rename back function
FOR-534 : https://jira.support-ent.fr/browse/FOR-534
=> fix(matrix): [#FOR-534] fix matrix duplication and rename back function

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/models/Model.java, common/src/main/java/fr/openent/form/core/models/Question.java, common/src/main/java/fr/openent/form/core/models/ShareObject.java, common/src/main/java/fr/openent/form/helpers/RightsHelper.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java, formulaire/src/main/java/fr/openent/formulaire/security/CustomShareAndOwner.java, formulaire/src/main/resources/sql/020-update-current-sharing.sql
Improve security on getForm API point.
Now you can only get a form you're owner of or one shared to you.
- Connect with a user
- Try to open one of your forms (shared or orwner), it should work
- Try to get one to someone else (by changing the form id in the URL), it shouldn't work
FOR-535 : https://jira.support-ent.fr/browse/FOR-535
=> fix(security): [#FOR-535] fix security access to getForm API function

common/src/main/resources/ts/services/FormService.ts, formulaire/src/main/resources/public/template/containers/edit-form.html, formulaire/src/main/resources/public/template/containers/prop-form.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/controllers/form-prop.ts, formulaire/src/main/resources/public/ts/directives/question/index.ts, formulaire/src/main/resources/public/ts/directives/question/question-item.ts, formulaire/src/main/resources/public/ts/directives/question/question-title.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-matrix.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-multipleanswer.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer-radio.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer.ts, formulaire/src/main/resources/public/ts/directives/section-item.ts
- When editing form, desired actions now trigger the navigation-guard system and others don't
- Same when editing form props
- Same when responding to a form
https://confluence.support-ent.fr/display/FOR/Alertes+changement+de+page
FOR-505 : https://jira.support-ent.fr/browse/FOR-505
FOR-409 : https://jira.support-ent.fr/browse/FOR-409
=> fix(navigation-guard) : [#FOR-505] fix navigation-guard behaviours

formulaire/src/main/resources/public/ts/directives/question/question-item.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor.ts
- fix step value checking for cursor questions
- change question-type-cursor directive structure
FOR-543 : https://jira.support-ent.fr/browse/FOR-543
=> fix(cursor): [#FOR-543] fix step value checking for cursor questions

formulaire-public/src/main/resources/i18n/en.json, formulaire-public/src/main/resources/i18n/fr.json, formulaire-public/src/main/resources/i18n/timeline/en.json, formulaire-public/src/main/resources/i18n/timeline/fr.json, formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire-public/src/main/resources/public/ts/directives/public-recap-question-item.ts
fix i18n for formulaire-public
FOR-545 : https://jira.support-ent.fr/browse/FOR-545
=> fix(i18n): [#FOR-545] fix i18n for formulaire-public

common/src/main/resources/ts/utils/public.ts, formulaire-public/src/main/java/fr/openent/formulaire_public/service/impl/DefaultResponseService.java, formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire-public/src/main/resources/public/ts/directives/public-matrix.ts, formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/directives/question/question-item.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts
When two cursors were following, the values were influenced by the prop min and max of the other one.
We had to change behaviour when two question with same type are following from the classic one when the questions are different type. 
FOR-546 : https://jira.support-ent.fr/browse/FOR-546
=> fix(cursor): [#FOR-546] fix cursor response value in formulaire-public

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
When duplicating a matrix not saved yet, some id prop were missing to correctly save lines of the matrixes so we added them.
FOR-552: https://jira.support-ent.fr/browse/FOR-552
=> fix(matrix): [#FOR-552] fix matrix duplication

formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFormServiceTest.java
Forms sent without a correct update of their "sent" prop will now be available in the linker.
FOR-488 : https://jira.support-ent.fr/browse/FOR-488
=> fix(linker): [#FOR-488] fix available forms in linker

formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor.ts
In cursor questions we block the possibility to have the min value equal the max value cause it would make no sense.
FOR-553 : https://jira.support-ent.fr/browse/FOR-553
=> fix(cursor): [#FOR-553] block same value for min and max in cursor question

common/src/main/java/fr/openent/form/core/constants/Constants.java, common/src/main/java/fr/openent/form/core/constants/Dates.java, common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/enums/ChoiceTypes.java, common/src/main/java/fr/openent/form/core/enums/RgpdLifetimes.java, common/src/main/java/fr/openent/form/core/models/Captcha.java, common/src/main/java/fr/openent/form/core/models/Delegate.java, common/src/main/java/fr/openent/form/core/models/Distribution.java, common/src/main/java/fr/openent/form/core/models/Folder.java, common/src/main/java/fr/openent/form/core/models/Form.java, common/src/main/java/fr/openent/form/core/models/FormElement.java, common/src/main/java/fr/openent/form/core/models/FormShare.java, common/src/main/java/fr/openent/form/core/models/Model.java, common/src/main/java/fr/openent/form/core/models/Question.java, common/src/main/java/fr/openent/form/core/models/QuestionChoice.java, common/src/main/java/fr/openent/form/core/models/QuestionType.java, common/src/main/java/fr/openent/form/core/models/RelFormFolder.java, common/src/main/java/fr/openent/form/core/models/Response.java, common/src/main/java/fr/openent/form/core/models/ResponseFile.java, common/src/main/java/fr/openent/form/core/models/Section.java, common/src/main/java/fr/openent/form/core/models/ShareGroup.java, common/src/main/java/fr/openent/form/core/models/ShareMember.java, common/src/main/java/fr/openent/form/core/models/ShareObject.java, common/src/main/java/fr/openent/form/core/models/ShareUser.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionChoiceController.java, formulaire/src/main/java/fr/openent/formulaire/helpers/DataChecker.java
We added models for all Formulaire entity defined in BDD
FOR-362 : https://jira.support-ent.fr/browse/FOR-362
=> feat(models): [#FOR-362] add back models

common/src/main/resources/ts/core/constants/constants.ts, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/question-item.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor.ts
When creating and registering a cursor question without defining min, max and step, default values are used instead.
FOR-555 : https://jira.support-ent.fr/browse/FOR-555
=> fix(cursor): [#FOR-555] fix creation cursor question

formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor.ts
When people responded to a cursor question, in the creation view the owner had wrong values displayed
FOr-556 : https://jira.support-ent.fr/browse/FOR-556
=> fix(cursor): [#FOR-556] fix cursor values when has responses

common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/utils/formElement.ts, common/src/main/resources/ts/utils/index.ts, common/src/main/resources/ts/utils/ranking.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts
Add drag&drop in respond view for question type ranking
When you respond to a question type ranking, try to drag&drop your answer
[FOR-540](https://jira.support-ent.fr/browse/FOR-540)
=> feat(question-type-ranking): #FOR-540 drag&drop ranking's type responses

formulaire/src/main/resources/public/ts/directives/question/question-item.ts
Add class to hover cursor for duplicate, delete and cancel buttons
On create view, check if for question & section, when you hover mouse on duplicate, delete & cancel buttons, you have a cursor pointer
[FOR-537](https://jira.support-ent.fr/browse/FOR-537)
=> FOR-537 add class to hover btn

common/src/main/java/fr/openent/form/core/models/Model.java
Return toList and toJsonArray function for models in back when param is null.
FOR-362 : https://jira.support-ent.fr/browse/FOR-362
=> fid(models): [#FOR-362] fix models basic functions on null case

common/src/main/java/fr/openent/form/core/constants/Constants.java, common/src/main/java/fr/openent/form/core/constants/DateFormats.java, common/src/main/java/fr/openent/form/core/models/Distribution.java, common/src/main/java/fr/openent/form/core/models/Form.java, common/src/main/java/fr/openent/form/core/models/ResponseFile.java, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseFileController.java, formulaire/src/main/java/fr/openent/formulaire/export/FormResponsesExportCSV.java, formulaire/src/main/java/fr/openent/formulaire/export/FormResponsesExportPDF.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/main/resources/public/ts/directives/question/result-question-item.ts
Fix some minor issues with previous adidng of custom choices for certain types of questions :
- Improve syntax in CSV export
- Imrpove display conditions of custom responses in results view
FOR-282 : https://jira.support-ent.fr/browse/FOR-282
=> fix(choices): [#FOR-282] fix export for questions with custom choices

formulaire/src/main/resources/sql/020-update-current-sharing.sql
Add "DISTINCT" in request to prevent and fix duplicate issue
[FOR-561](https://jira.support-ent.fr/browse/FOR-561)
=> fix(update-current-sharing): #FOR-561 fix duplicate issue

common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/utils/graph.ts, formulaire/src/main/resources/public/ts/directives/question/result-question-item.ts, tsconfig.json
Build bar chart grouped to result view
[FOR-453](https://jira.support-ent.fr/browse/FOR-453)
=> FOR-453 Result view

common/src/main/resources/ts/utils/utils.ts, formulaire/src/main/resources/public/template/lightbox/form-check-remind.html, formulaire/src/main/resources/public/ts/controllers/forms-list.ts
We previously tried to separate name and surname but there's not enough formatting of the fullname to do it properly.
So now we display directly the fullname of the responder in the Remind lighbox.
FOR-562 : https://jira.support-ent.fr/browse/FOR-562
=> fix(reminder): [#FOR-562] fix displaying of names in reminder

formulaire/src/main/resources/sql/020-update-current-sharing.sql
Fix SQL script.
The goal was to add a sharing right to all the users already having some specifics rights.
But in order to do that we first need to filter the users who already had this new right to avoid duplicate insert.
It's an improvment of the #211 
FOR-561 : https://jira.support-ent.fr/browse/FOR-561
=> fix(sql): [#FOR-561] fix duplicate issues in updating sharing script

formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-ranking/question-type-ranking.directive.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-ranking/question-type-ranking.html
Initialize variables 'direction' in my directive, add choice_position in response + add some types
In the create view, try to reorganize question choice with arrows
[FOR-452](https://jira.support-ent.fr/browse/FOR-452)
=> fix(question-type-ranking): #FOR-452 initialize variable direction

formulaire/src/main/resources/public/ts/directives/question/recap-question-item.ts
Add a filter to only display question type ranking in recap
Go on the recap view and check if you only have your responses to the ranking's question type
[FOR-451](https://jira.support-ent.fr/browse/FOR-451)
=> fix(question-type-ranking): #FOR-451 add a filter for type ranking

formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
- Fix checking of different types (Integer and Long)
- Improve some logs
FOR-572 : https://jira.support-ent.fr/browse/FOR-572
=> fix(matrix): [#FOR-572] fix matrix response saving

formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json
Edit i18n
When you create a new form, there is an icone "i" to explain specificity about public formulaire, check if description is correctly update
[FOR-571](https://jira.support-ent.fr/browse/FOR-571)
=> feat(i18n): #FOR-571 edit formulaire public description

formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultResponseService.java
Add order by choice_position to handle export CSV for ranking's question type
Export result of form with at less one ranking's question type , and check if answer is display in the right order
[FOR-278](https://jira.support-ent.fr/browse/FOR-278)
=> fix(exportCSV): #FOR-278 edit exportCVSResponses

formulaire-public/src/main/resources/public/ts/controllers/recap.ts, formulaire/src/main/resources/public/ts/controllers/recap-questions.ts
When sending responses for a form containing mandatory questions with only custom answers, these were not counted and thus the mandatoy question were not considered answered. Now it includes it.
FOR-282 : https://jira.support-ent.fr/browse/FOR-282
=> fix(custom_answer): [#FOR-282] fix saving for mandatory question with custom answer

formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.directive.ts
Fix drag and drop in preview
FOR-452 : https://jira.support-ent.fr/browse/FOR-452
=> fix(ranking): [#FOR-452] fix drag and drop in preview

formulaire-public/src/main/resources/public/ts/directives/public-recap-question-item.ts, formulaire/src/main/resources/public/ts/directives/question/recap-question-item.ts
Fix display responses for ranking question in recap.
FOR-451 : https://jira.support-ent.fr/browse/FOR-451
=> fix(ranking): [#FOR-451] fix recap

package.json
Update ApexChart version
FOR-453 : https://jira.support-ent.fr/browse/FOR-453
=> fix(graph): [#FOR-453] update apexchart version

formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-ranking/question-type-ranking.directive.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.directive.ts
-Fix placeholder for question type ranking
-Fix placeholder for all questions on response side
FOR-578 : https://jira.support-ent.fr/browse/FOR-578
=> fix(placeholder): [#FOR-578] fix some placeholders

common/src/main/resources/ts/utils/graph.ts
Improve ranking graph, remove dataLabels and remove redontant information in tooltip
[FOR-453](https://jira.support-ent.fr/browse/FOR-453)
=> feat(graph): #FOR-453 remove dataLabels + edit tooltip

formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.directive.ts
Init drag&drop 
[FOR-451](https://jira.support-ent.fr/browse/FOR-451)
=> fix(drag&drop): #FOR-451 init drag&drop

common/src/main/java/fr/openent/form/core/constants/Fields.java, formulaire/src/main/java/fr/openent/formulaire/export/FormResponsesExportPDF.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultResponseService.java, formulaire/src/main/resources/public/template/pdf/results.xhtml, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.html, formulaire/src/main/resources/public/ts/directives/question/result-question-item.ts
- Add custom_answers to export PDF results
- In result view, we do not display only custom_answers when people used it (we had empty line for every response before)
FOR-579 : https://jira.support-ent.fr/browse/FOR-579
=> fix(custom_answers): [#FOR-579] fix results views for custom_answers

formulaire/src/main/resources/public/ts/controllers/form-results.ts, formulaire/src/main/resources/public/ts/directives/question/result-question-item/result-question-item.html
- Standardize graph display
- Fix responses included in calculs (we reject the ones not finished)
FOR-582 : https://jira.support-ent.fr/browse/FOR-582
=> fix(graph): [#FOR-582] fix graph values and standardize display

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
Added != null in my condition to avoid problems when the result is 0 and my result is considered null
Try to create a new cursor's question, with min value at 0 and check if you can save it. (you should be able to do this)
[FOR-583](https://jira.support-ent.fr/browse/FOR-583)
=> feat(graph): #FOR-583 fix condition if result is equal to 0

formulaire-public/src/main/resources/public/ts/directives/public-recap-question-item.ts
Edit ng-repeat to filter responses recap in formulaire-public
[FOR-451](https://jira.support-ent.fr/browse/FOR-451)
=> fix(question-type-ranking): #FOR-451 add filter in formulaire-public

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/resources/ts/utils/graph.ts, formulaire/src/main/java/fr/openent/formulaire/export/FormResponsesExportPDF.java, formulaire/src/main/resources/public/template/pdf/results.xhtml, formulaire/src/main/resources/public/ts/directives/question/result-question-item/result-question-item.html
Added average value in export PDF for question cursor type
- Respond to a question type cursor
- Go to result page and export PDF
FOR-582 : https://jira.support-ent.fr/browse/FOR-582
FOR-585 : https://jira.support-ent.fr/browse/FOR-585
=> fix(export-pdf): #FOR-582 add average in PDF export

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
Add exception to not save when click on it
Create a question type freetext and click on "insert an image" in the editor
When the image is inserted, you can click on it and you have the "retouch" option. You should have editor image who open
[FOR-558](https://jira.support-ent.fr/browse/FOR-558)
=> fix(editor): #FOR-558 fix image editing

formulaire/src/main/resources/public/template/lightbox/questions-reorganization.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
Add condition to save if you are in organization pop up
[FOR-558](https://jira.support-ent.fr/browse/FOR-558)
=> fix(editor): #FOR-558 add condition to handle organize

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/enums/ApiVersions.java, common/src/main/resources/ts/services/QuestionChoiceService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionChoiceController.java, formulaire/src/main/java/fr/openent/formulaire/helpers/ApiVersionHelper.java, formulaire/src/main/java/fr/openent/formulaire/service/SectionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultSectionService.java
With mobile ecosystem, users can have old front versions when back keeps updating with new desktop versions.
In desktop version 1.9.0 we got a breaking change : a SQL column is renamed from "**next_section_id**" to "**next_form_element_id**".
Thus, we need to make API versionning to adapt the call and respond between the BDD and the front.
The API versionning works with a header specifying an API version. Here the new one is called "1.9" and there's nothing to do when API is called with this header.
But if the header specified an older version or nothing at all, we adapt the content in controller.
FOR-594 : https://jira.support-ent.fr/browse/FOR-594
=> feat(apiVersion): [#FOR-594] add api versioning

common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/models/QuestionChoice.ts, formulaire/src/main/resources/public/ts/directives/question/question-item/question-item.directive.ts
When we switch a question to condiitonal or not, we now keep the memory of the elements targeted
FOR-604 : https://jira.support-ent.fr/browse/FOR-604
=> fix(targetting): [#FOR-604] fix conditional question initialization

formulaire/src/main/resources/public/template/containers/edit-form.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
Add id to button 'createNewElt' to exclude it from isInDontSave function, to fix issue in form when you add new question, precious was not saved.
[FOR-593](https://jira.support-ent.fr/browse/FOR-593)
=> fix(saveForm): #FOR-593 exclude createNewElt to isInDontSave

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/enums/I18nKeys.java, formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/FormulaireRepositoryEvents.java
Display & manage target to conditionals questions
In a form, create a conditional question, with target and export your form. Your target should be next to the choice of each relevant question.
[FPR-601](https://jira.support-ent.fr/browse/FOR-601)
=> feat(conditionalQuestion): #FOR-601 display conditional questions

common/src/main/java/fr/openent/form/core/constants/Fields.java, formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/main/resources/public/template/lightbox/form-export.html, formulaire/src/main/resources/public/template/pdf/questions.xhtml, formulaire/src/main/resources/public/ts/controllers/forms-list.ts, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java
Template for export question's form PDF
[FOR-597](https://jira.support-ent.fr/browse/FOR-597)
=> feat(templatePDF): #FOR-597 Template PDF

common/src/main/resources/ts/utils/formElement.ts
fix DnD question outside section
FOr-605 : https://jira.support-ent.fr/browse/FOR-605
=> fix(DnD): [#FOR-605] fix DnD question outside section

common/src/main/resources/ts/models/FormElement/Section.ts
Fix blank choice in list of targets for sections
FOR-606 : https://jira.support-ent.fr/browse/FOR-606
=> fix(targeting): [#FOR-606] fix blank choice in list of targets for sections

formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
Fix issue to get right section_id, to get questions from section
Try to export form with question in section
[FOR-602](https://jira.support-ent.fr/browse/FOR-602)
=> fix(exportPDF): #FOR-602 fix get question(s) from section

formulaire/src/main/resources/public/template/lightbox/form-export.html
Add balise <br> to separate title and description
[FOR-598](https://jira.support-ent.fr/browse/FOR-598)
=> fix(templatePDF): #FOR-598 separate title and description

formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultDistributionService.java, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.directive.ts
Problem 1 : Store ranking form without sending it back to the author
When a form of type "RANKING" was filled by a responder and closed without saving it, the user responses were unsorted when he came back to it.
The problem was located in front logic to get the responses from db and store them well in the responses of the directive.
Now The responses remain in the same order as the user left them the last time he filled out the form.
Problem2 : Store ranking form and sending it back to the author
When a ranking form was stored and sent to the author. If we wanted to re-open it, the responses were in the wrong order.
When storing and sending the filled form, a new copy of the distribution (or shared form) is created with the help of pg query. 
The problem was located in the back-end …
=> fix: #FOR-623 set good responses in directive to sort them well according to their choice position

formulaire/src/main/java/fr/openent/formulaire/controllers/DistributionController.java, formulaire/src/main/java/fr/openent/formulaire/service/DistributionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultDistributionService.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultDistributionServiceTest.java
By resolving https://jira.support-ent.fr/browse/FOR-623,
Quentin asked for transforming the method "duplicateWithResponses" in Distribution service with the help of future return statement and to do associated unit tests.
https://jira.support-ent.fr/browse/FOR-624
=> feat(DistributionService) : #FOR-624 transform duplicateWithResponses method's signature with future

formulaire/src/main/java/fr/openent/formulaire/service/impl/ImportExportService.java
Fix import forms
FOr-629 : https://jira.support-ent.fr/browse/FOR-629
=> fix(import/export): [#FOR-629] fix import

common/src/main/java/fr/openent/form/core/constants/Fields.java, formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java, formulaire/src/main/resources/public/template/pdf/questions.xhtml
Added a condition to determine input's type to display
[FOR-616](https://jira.support-ent.fr/browse/FOR-616)
=> feat(matrix-multipleanswer): #FOR-616 question export PDF

common/src/main/resources/ts/utils/graph.ts
Remove toolbar from graph
[FOR-612](https://jira.support-ent.fr/browse/FOR-612)
=> fix(matrix-multipleanswer): #FOR-612 remove toolbar from graph

formulaire-public/src/main/resources/public/template/containers/respond-question.html
Display respond view in public form when question is in a section
[FOR-614](https://jira.support-ent.fr/browse/FOR-614)
=> fix(matrix-multipleanswer): #FOR-614 respond view in form public

formulaire/src/main/resources/public/ts/directives/question/respond-matrix/respond-matrix.directive.ts
Missing a letter on the $onChanges to correctly  init information
Create a form with at least two matrix questions in a row, and then in respond view, confirm that you can select your answer correctly.
[FOR-630](https://jira.support-ent.fr/browse/FOR-630)
=> fix(matrix-multipleanswer): #FOR-630 fix initRespondMatrix

common/src/main/resources/ts/utils/graph.ts, formulaire-public/src/main/resources/public/ts/directives/public-recap-question-item/public-recap-question-item.directive.ts, formulaire/src/main/resources/public/ts/directives/question/recap-question-item/recap-question-item.directive.ts
Force whole number in yaxis insteed of decimal one, and fix wrong i18n
[FOR-631](https://jira.support-ent.fr/browse/FOR-631)
=> fix(matrix-multipleanswer): #FOR-631 force whole number in yaxis

formulaire/src/main/resources/public/ts/controllers/form-tree-view.ts
*Now the graph is centered when displaying the form workflow.*
*Go to form module and then edit a form ang click on "Visualiser le parcours" to display the vue of graph.*
[FOR-645](https://jira.support-ent.fr/browse/FOR-645)
=> fix(formTree): #FOR-645 refactor tree display and add center position to the graph when init

formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/template/containers/tree-view.html, formulaire/src/main/resources/public/ts/controllers/form-tree-view.ts
*Add informations for the user to drag and zoom in graph vue.*
*This PR is linked to CSS PR :*
https://github.com/CGI-OPEN-ENT-NG/entcore-css-lib/pull/79
Open a form to edit it and click on "visualiser le parcours"
[FOR-647](https://jira.support-ent.fr/browse/FOR-647)
=> feat(treeForm): #FOR-647 add legend informations to zoom and drag when in graph vue

README.md
*In form module, we couldn't import a zip form because of a lack of configuration.*
*Indeed, the import is handled by a service in entcore which makes a call to a conf called publicConf so we have to add it.*
*This task is now explained in the form README file*
Add the conf in ent-core.json and import a form into .zip format.
[FOR-620](https://jira.support-ent.fr/browse/FOR-620)
=> fix(import): #FOR-620 add conf into "ent-core.json" for the module "entcore-archive" to make local import work.

common/src/main/resources/ts/models/FormElement/FormElement.ts, common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/models/FormElement/Section.ts, common/src/main/resources/ts/models/QuestionChoice.ts, common/src/main/resources/ts/services/FormElement/FormElementService.ts, common/src/main/resources/ts/services/FormElement/QuestionService.ts, common/src/main/resources/ts/services/FormElement/SectionService.ts, common/src/main/resources/ts/services/QuestionChoiceService.ts
When saving an element, the payload was containing a nested prop leading to a 413 error (payload too big).
Fortunately we didn't need this nested prop so we created new specifics models for payloads : 
- SectionPayload
- QuestionPayload
- QuestionChoicePayload
FOR-663 : https://jira.support-ent.fr/browse/FOR-663
FOR-638 : https://jira.support-ent.fr/browse/FOR-638
=> fix(payloads): [#FOR-663] create payload models for Section, Question and QuestionChoice

common/src/main/resources/ts/models/QuestionChoice.ts
Add image prop to QuestionChoicePayload model
FOR-663 : https://jira.support-ent.fr/browse/FOR-663
=> fix(payloads): [#FOR-663] add image prop to QuestionChoicePayload model

README.md
Update conf of the modules for conf.proprieties
=> update(readme): specify conf of the module for conf.proprieties

common/src/main/resources/ts/models/QuestionChoice.ts, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
Now question duplication also takes car of images
FOR-682 : https://jira.support-ent.fr/browse/FOR-682
=> fix(duplication): [#682] fix image duplication for choices

formulaire-public/src/main/resources/public/ts/directives/public-recap-question-item/public-recap-question-item.html, formulaire-public/src/main/resources/public/ts/directives/public-respond-question-item/public-respond-question-item.directive.ts, formulaire-public/src/main/resources/public/ts/directives/public-respond-question-item/public-respond-question-item.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/recap-question-item/recap-question-item.html, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.directive.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.html
New feature to add an image in addition to the label for question type singleanswer; the label is mandatory if there is an image.
[schema BDD update](https://confluence.support-ent.fr/pages/viewpage.action?pageId=67210096)
In a form with a question type singleanswer, you now can view image and label to respond
[FOR-669](https://jira.support-ent.fr/browse/FOR-669)
=> feat(img-singleanswer): #FOR-669 response image addition view

formulaire/src/main/resources/public/ts/directives/question/question-type.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer/question-type-singleanswer.directive.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer/question-type-singleanswer.html
Allow the images added for this question type to be public and thus to be seen in a public response.
FOR-665 : https://jira.support-ent.fr/browse/FOR-665
=> feat(img-singleanswer): [#FOR-665] allow public images

formulaire/src/main/resources/public/ts/directives/question/question-item/question-item.html
Add missing closing parenthesis 
In a multiple response type question, try adding an image but no label: you should get an error indicating that it is not possible
There is no ticket, I discovred this little regression by myself
=> fix(img-singleanswer): #FOR-670 add missing closing parenthesis

common/src/main/java/fr/openent/form/core/constants/Fields.java, formulaire/src/main/java/fr/openent/formulaire/Formulaire.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/UtilsController.java, formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java, formulaire/src/main/resources/public/template/pdf/questions.xhtml
We added image gestion and displaying in PDF export for questions of type :
- Single answer radio
- Multiple answer
**Pour info :** Un ticket refacto de ce fichier d'export PDF est prévu pour la suite, c'est pour ça que j'ai recup/réutilisé des bouts de code déjà présent sans refacto. L'idée était juste d'ajouter la feature sans risque de casser l'existant qui va être tout refacto dans tous les cas
FOR-654 : https://jira.support-ent.fr/browse/FOR-654
FOR-667 : https://jira.support-ent.fr/browse/FOR-667
=> feat(pdf): [#FOR-654] add images to PDF export for question choices

formulaire-public/src/main/resources/public/ts/directives/public-respond-question-item/public-respond-question-item.html, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.html
In preview and response view we improved the design and CSS
CSS : https://github.com/CGI-OPEN-ENT-NG/entcore-css-lib/pull/82
FOR-669 : https://jira.support-ent.fr/browse/FOR-669
=> fix(response): [#FOR-669] fix response CSS for QCR and QCM with images

formulaire/src/main/java/fr/openent/formulaire/controllers/MonitoringController.java, formulaire/src/main/java/fr/openent/formulaire/service/MonitoringService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultMonitoringService.java
Modification of the monitoring API to retrieve and verify script information, especially in the ODE preprod/prod system (date and filename).
FOR-683 : https://jira.support-ent.fr/browse/FOR-683
=> feat(monitoring): Add retrieval script informations

.github/workflows/dev-check-repository.yml, .gitignore, build.sh, docker-compose.yml, formulaire/src/main/resources/public/sass/global/_formulaire.scss, formulaire/src/main/resources/public/sass/global/components/_dominos.scss, formulaire/src/main/resources/public/sass/global/components/_edit-form.scss, formulaire/src/main/resources/public/sass/global/components/_folder.scss, formulaire/src/main/resources/public/sass/global/components/_icon.scss, formulaire/src/main/resources/public/sass/global/components/_main.scss, formulaire/src/main/resources/public/sass/global/components/_respond-question.scss, formulaire/src/main/resources/public/sass/global/components/_result-form.scss, formulaire/src/main/resources/public/sass/global/components/containers/_index.scss, formulaire/src/main/resources/public/sass/global/components/containers/cursor/_question-type-cursor.scss, formulaire/src/main/resources/public/sass/global/components/containers/tree/_tree.scss, formulaire/src/main/resources/public/sass/index.scss, formulaire/src/main/resources/view-src/formulaire.html, formulaire/src/main/resources/view-src/formulaire_public.html, jest.config.js, package.json
*Migrate css inside the module as mentioned in the documentation :
https://confluence.support-ent.fr/display/DN/Packager+du+CSS+dans+un+module*
*Make a css change like a red backround color and then buils css from the build.sh of the module and watch the changes in the browser.*
[FOR-684](https://jira.support-ent.fr/browse/FOR-684)
=> chore(css): #FOR-684 migrate css within module

formulaire/src/main/resources/public/sass/global/_formulaire.scss, formulaire/src/main/resources/public/template/lightbox/form-export.html, formulaire/src/main/resources/public/ts/controllers/forms-list.ts
When opening lightbox for export questions we have set a default selection (on ZIP format). And if we change selection, close lightbox and open again, the selection is set to default value again.
FOR-674 : https://jira.support-ent.fr/browse/FOR-674
=> fix(export): [#FOR-674] set default selection for export questions

formulaire-public/src/main/resources/public/ts/controllers/recap.ts
Add function  "getHtmlDescription" in public part of form module to display the description of a section in a public form when answering it.
Create a form with a section and its description. Share this form to get the public link, copy the link in URL to reach the form and watch if the description of section is still there.
[FOR-640](https://jira.support-ent.fr/browse/FOR-640)
=> fix(description): #FOR-640 display the description of a section in public form when responding

formulaire-public/src/main/resources/view-src/formulaire_public.html, formulaire/src/main/resources/public/sass/index.scss, formulaire/src/main/resources/public/sass/panda/_formulaire.scss, formulaire/src/main/resources/public/template/containers/edit-form.html, formulaire/src/main/resources/public/template/containers/prop-form.html, formulaire/src/main/resources/view-src/formulaire.html
Fix bugs on panda theme (theme 1D) :
- migration was missing last panda theme dev
- we added some "ellipsis" for long text badly displayed
- we added some tooltip to display these text when ellipsed
FOR-573 : https://jira.support-ent.fr/browse/FOR-573
=> fix(panda): [#FOR-573] fix migration CSS 1D and fix bugs 1D

build.sh, docker-compose.yml
Fix yarn environement build and errors in build.sh
=> chore(): fix yarn environment build

formulaire/src/main/resources/public/ts/directives/question/question-title/question-title.html, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-multipleanswer/question-type-multipleanswer.html, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer/question-type-singleanswer.html
Fix icon display for QCM and QCR images with panda theme
FOR-573 : https://jira.support-ent.fr/browse/FOR-573
Retours du ticket FOR-684 : https://jira.support-ent.fr/browse/FOR-684
=> fix(css): [#FOR-684] fix icon display for QCM and QCR images

formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java
- Remove unecessary info from logs
- Try a new improvement for logs
FOR-634 : https://jira.support-ent.fr/browse/FOR-634
=> fix(logs): [#FOR-634] improve logs

common/src/main/java/fr/openent/form/core/models/Captcha.java, common/src/main/java/fr/openent/form/core/models/Delegate.java, common/src/main/java/fr/openent/form/core/models/Distribution.java, common/src/main/java/fr/openent/form/core/models/Folder.java, common/src/main/java/fr/openent/form/core/models/Form.java, common/src/main/java/fr/openent/form/core/models/FormShare.java, common/src/main/java/fr/openent/form/core/models/IModel.java, common/src/main/java/fr/openent/form/core/models/Question.java, common/src/main/java/fr/openent/form/core/models/QuestionChoice.java, common/src/main/java/fr/openent/form/core/models/QuestionType.java, common/src/main/java/fr/openent/form/core/models/RelFormFolder.java, common/src/main/java/fr/openent/form/core/models/Response.java, common/src/main/java/fr/openent/form/core/models/ResponseFile.java, common/src/main/java/fr/openent/form/core/models/Section.java, common/src/main/java/fr/openent/form/core/models/ShareGroup.java, common/src/main/java/fr/openent/form/core/models/ShareMember.java, common/src/main/java/fr/openent/form/core/models/ShareObject.java, common/src/main/java/fr/openent/form/core/models/ShareUser.java, common/src/main/java/fr/openent/form/helpers/IModelHelper.java, common/src/main/java/fr/openent/form/helpers/StringHelper.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FolderController.java, formulaire/src/main/java/fr/openent/formulaire/service/FolderService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFolderService.java
- Block the user to access folder not owned by API call
- Rename Model interface to IModel
- Add helpers for model use
FOR-635 : https://jira.support-ent.fr/browse/FOR-635
=> fix(folders): [#FOR-635] forbid user to access not owned folder infos

common/src/main/java/fr/openent/form/core/constants/Constants.java, common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/models/Distribution.java, common/src/main/java/fr/openent/form/core/models/Form.java, common/src/main/java/fr/openent/form/core/models/IModel.java, common/src/main/java/fr/openent/form/core/models/Question.java, common/src/main/java/fr/openent/form/core/models/Section.java, common/src/main/java/fr/openent/form/helpers/IModelHelper.java, formulaire/src/main/java/fr/openent/formulaire/Formulaire.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FolderController.java, formulaire/src/main/java/fr/openent/formulaire/service/FolderService.java, formulaire/src/main/java/fr/openent/formulaire/service/FormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFolderService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultNotifyService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/FormulaireApplicationStorage.java, formulaire/src/main/resources/i18n/timeline/en.json, formulaire/src/main/resources/i18n/timeline/fr.json, formulaire/src/main/resources/view-src/notify/infected_file_notification.html, formulaire/src/main/resources/view-src/notify/infected_file_notification.json, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultDistributionServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFolderServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFormServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionChoiceServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultResponseServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/FormulaireApplicationStorageTest.java
Catch infected file alert and send a notification to all the contibutors of the form when it happens.
FOR-592 : https://jira.support-ent.fr/browse/FOR-592
=> feat(files): [#FOR-592] send notification when infected file is upload

common/src/main/java/fr/openent/form/core/constants/DateFormats.java, formulaire-public/src/main/java/fr/openent/formulaire_public/controllers/FormController.java
Sign cookies in server side to improve security
A more complete description is available on this page : https://confluence.support-ent.fr/pages/viewpage.action?pageId=158602917
FOR-591 : https://jira.support-ent.fr/browse/FOR-591
=> fix(cookies): [#FOR-591] sign cookies for public forms

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/enums/I18nKeys.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java, formulaire/src/main/java/fr/openent/formulaire/export/FormResponsesExportCSV.java, formulaire/src/main/java/fr/openent/formulaire/export/FormResponsesExportPDF.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultSectionService.java, formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/template/pdf/questions.xhtml, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java
The entire FormQuestionsExportPDF has been refactorized
Create a form with all kind of form elements and export it. Check if all elements are present in PDF and well displayed.
[FOR-609](https://jira.support-ent.fr/browse/FOR-609)
=> fix(exportPDF): #FOR-609 factorize whole exportQuestionPDF 

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/models/IModel.java, common/src/main/java/fr/openent/form/core/models/Question.java, common/src/main/java/fr/openent/form/core/models/QuestionSpecificFields.java, common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/models/QuestionSpecificFields.ts, common/src/main/resources/ts/services/FormElement/FormElementService.ts, common/src/main/resources/ts/services/FormElement/QuestionService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionService.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionSpecificFieldsService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionSpecificFieldsService.java, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionSpecificServiceTest.java
Fix saving for matrix questions. Problem was the lines were saved one by one. So we improved the code to be able to save multiple questions at the same time.
Includes a bit of refactoring for Question and QuestionSpecificFields models and services
FOR-693 : https://jira.support-ent.fr/browse/FOR-693
=> fix(matrix): [#FOR-693] fix matrix saving

formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
Before in code, jsonArray correspoding to the key "questions" was always overwritten because the case was not handled.
Now we check if the key exists and add the question or create the key with new jsonArray if not.
Create a form with a section and several questions of any kind in that section. Then export it.
[FOR-609](https://jira.support-ent.fr/browse/FOR-609)
=> fix(exportPDF): #FOR-609 export section with several questions

common/src/main/java/fr/openent/form/core/models/Question.java
When saving a question, we pass through the createQuestion method which return a promise of Question toJson().
The custom method toJson transforms the Model question in a jsonObject but we tried to put an instance of Model (QuestionSpecifiFields) directly as a value in our JsonObject which leaded to some errors when question is type of cursor).
Now, before inserting it in the JsonObject, we transform our instance of QuestionSpecificField in a Json too.
Create a new form and add cursorQuestions form elements, then save the form.
=> fix(cursor): #FOR-706 save cursor question

formulaire/src/main/java/fr/openent/formulaire/export/FormResponsesExportPDF.java
Exporting the responses of a form in pdf  didn't work because of applying a string replace on a null value in a JsonObject.
So we add a condition to check if the value is not null.
Create a form (public is more simple as you don't need to share it). Open the link of the form and answer it then save your answers.
When goig back to the creator's interface, select the form and see the results then click on export in pdf.
=> fix(exportResponsePDF): #FOR-711 add condition to check if section contains a description to avoid NPE

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
When in peviewmode of form edition, we can simulate a form answering.
If we have a question (conditional) which lead to the end of the form and when we click on "suivant", it must send us to the page "fin du recap" but it diddn't.
We add a condition to check if the nextPosition == null to handle this case.
Create a form with radio questions. Pass these questions to conditional, one of the condititionnal questions must lead to the end of the form. Then, click on "aperçu" and choose the answer that must lead to the end of the recap.
[FOR-712](https://jira.support-ent.fr/browse/FOR-712)
=> fix(preview): #FOR-712 add case of conditional question leading to the end of form in preview mode

formulaire-public/src/main/resources/public/ts/services/FormService.ts
When we respond to a public form and try to open it again we get to an error page.
A notify banner was also display. Now the notify is delete and we only have the error page.
FOR-591 : https://jira.support-ent.fr/browse/FOR-591
=> fix(formulaire-public): [#FOR-591] delete double error message

common/src/main/java/fr/openent/form/core/enums/Actions.java, common/src/main/java/fr/openent/form/core/models/IModel.java, common/src/main/java/fr/openent/form/core/models/Question.java, common/src/main/java/fr/openent/form/core/models/QuestionSpecificFields.java, common/src/main/java/fr/openent/form/core/models/TransactionElement.java, common/src/main/java/fr/openent/form/helpers/TransactionHelper.java, common/src/main/java/fr/openent/form/helpers/UtilsHelper.java, common/src/main/resources/ts/models/FormElement/FormElement.ts, common/src/main/resources/ts/models/FormElement/FormElements.ts, common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/models/QuestionChoice.ts, common/src/main/resources/ts/models/QuestionSpecificFields.ts, common/src/main/resources/ts/services/FormElement/QuestionService.ts, formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire-public/src/main/resources/public/ts/directives/public-respond-question-item/public-respond-question-item.directive.ts, formulaire-public/src/main/resources/public/ts/directives/public-respond-question-item/public-respond-question-item.html, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionService.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionSpecificFieldsService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionSpecificFieldsService.java, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/controllers/forms-list.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/directives/question/question-item/question-item.directive.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor/question-type-cursor.directive.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-cursor/question-type-cursor.html, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.directive.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.html, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionSpecificServiceTest.java
The question type cursor was not working properly anymore. It revealed a modeling issue we fixed.
FOR-710 : https://jira.support-ent.fr/browse/FOR-710
=> fix(specific_fields): [#FOR-710] fix modeling for question specific fields

common/src/main/resources/ts/models/FormElement/Question.ts, common/src/main/resources/ts/models/FormElement/Section.ts
Fix matrix creation by improving QuestionPayload model
Needs https://github.com/OPEN-ENT-NG/form/pull/337 to be merged to works.
FOR-715 : https://jira.support-ent.fr/browse/FOR-715
=> fix(matrix): [#FOR-715] fix matrix creation

common/src/main/resources/ts/models/QuestionSpecificFields.ts
Fix creation cursor with no values or values equal to 0
FOR-706 : https://jira.support-ent.fr/browse/FOR-706
=> fix(cursor): [#FOR-706] fix cursor creation

formulaire/src/main/resources/public/ts/controllers/form-tree-view.ts
Add resize envent listener in DOM to apply center graph function whenever viewport width is changing.
Open an inspector and change viewport scale.
[FOR-649](https://jira.support-ent.fr/browse/FOR-649)
=> fix(responsive): #FOR-649 make tree responsive

formulaire/src/main/java/fr/openent/formulaire/security/CustomShareAndOwner.java
We improved sharing rights checking system to deal with a new specific case.
- respond to a form having a question type file and send your answers
- start modifying your response via the "My responses" pop up
- go to Results and try to download a file you gave earlier when answering the file type question
FOR-713 : https://jira.support-ent.fr/browse/FOR-713
=> fix(rights): [#FOR-713] improve sharing rights management

common/src/main/resources/ts/utils/graph.ts, formulaire/src/main/resources/public/sass/global/components/_result-form.scss, formulaire/src/main/resources/public/ts/directives/question/result-question-item/result-question-item.directive.ts, formulaire/src/main/resources/public/ts/directives/question/result-question-item/result-question-item.html
In results view, all the grpah questions was generated with ApexChart but one : the multipleanswer.
The graph was generated manually and we had a special portion of code dedicated to it.
We decided to harmonize averyhting by using ApexChart for thuis type of question too.
FOR-444 : https://jira.support-ent.fr/browse/FOR-444
=> fix(results): [#FOR-444] change graph result for multipleanswer by using apexchart

common/src/main/java/fr/openent/form/core/enums/I18nKeys.java, common/src/main/resources/ts/services/FormElement/QuestionService.ts, common/src/main/resources/ts/utils/data.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java, formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json
- Allows a specific error message when creating a question
- Display a specific message chen trying to duplicate a conditional question in a section
FOR-714 : https://jira.support-ent.fr/browse/FOR-714
=> fix(conditional): [#FOR-714] custom error message when creating question

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
Fix matrix creation when some lines are empty
FOr-715 : https://jira.support-ent.fr/browse/FOR-715
=> fix(matrix): [#FOR-715] fix matrix creation when some lines are empty

formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
In case some images are broken, missing or corrupt, PDF export fails. We now take care of this case, exporting anyway.
Try to export a form with image in PDF, you can use a form with missing image to confirm that it's fixed.
[FOR-729](https://jira.support-ent.fr/browse/FOR-729)
=> fix(exportPDF): #FOR-729 handle image missing or corrupted

formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseFileController.java, formulaire/src/main/java/fr/openent/formulaire/security/CustomShareAndOwner.java, formulaire/src/main/java/fr/openent/formulaire/service/ResponseFileService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultResponseFileService.java
When checking results of a form, the files corresponding to a response currently modified was not available to download, we fixed it.
FOR-713 : https://jira.support-ent.fr/browse/FOR-713
=> fix(results): [#FOR-713] fix download of files from results view

common/src/main/resources/ts/core/constants/constants.ts, common/src/main/resources/ts/models/Files.ts, common/src/main/resources/ts/models/index.ts, formulaire/src/main/resources/public/template/containers/preview-form.html, formulaire/src/main/resources/public/template/containers/respond-question.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.directive.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.html
Fix question files in sections, including 'Preview' page.
Creation, updating, deletion works well now, even for multiple question file in a row a in a same section or mix of this.
FOR-222 : https://jira.support-ent.fr/browse/FOR-222
=> fix(files): [#FOR-222] fix files question in sections

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/enums/ApiVersions.java, common/src/main/java/fr/openent/form/core/models/ApiVersion.java, common/src/main/resources/ts/services/FormElement/QuestionService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java, formulaire/src/main/java/fr/openent/formulaire/helpers/ApiVersionHelper.java
Implements a new API version (2.0) to counter changes made in formulaire version 1.11.2
FOR-733 : https://jira.support-ent.fr/browse/FOR-733
=> feat(apiVersion): [#FOR-733] create new api version (2.0)

common/src/main/resources/ts/utils/public.ts
To prevent redirect issue in formulaire-public, we define 'question' and 'section'
Create a public form with section and questions in and out the section, share the link and respond to it. We should be able de see all the sections & questions.
[FOR-742](https://jira.support-ent.fr/browse/FOR-742)
=> fix(public-form): #FOR-742 define form_element_type

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
To avoid a possible bad position, we recalculate them
Create a form with question and section and you should not have any issue to create new element
[FOR-746](https://jira.support-ent.fr/browse/FOR-746)
=> fix(form-editor): #FOR-746 prevent a possible wrong position

formulaire/src/main/java/fr/openent/formulaire/service/impl/FormulaireRepositoryEvents.java
Add a checking when exporting Formulaire data from Archive module. It now allows to export Formulaire data even if there's none and therefore allows Archive module code to flow normally.
FOR-749 : https://jira.support-ent.fr/browse/FOR-749
=> fix(export): [#FOR-749] fix Archive export when Formulaire has no data

formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java
When creating/duplicating a question in a section we do a checking to avoid to have two conditionnal question.
But the checking was wrong and threw errors when it should have. We fixed it.
- Create a form
- Create a section
- Add a conditionnal question inside
- Add a question inside that could be conditionnal (QCR, QCU)
- Duplicate this question
FOR-731 : https://jira.support-ent.fr/browse/FOR-731
=> fix(conditionnal): [#FOR-731] fix duplication of question in section

formulaire/src/main/resources/public/sass/global/components/_respond-question.scss, formulaire/src/main/resources/public/sass/global/components/containers/cursor/_question-type-cursor.scss, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.directive.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.html
Update pin size for cursor type questions.
The calculation is explained in the following documentation : https://confluence.support-ent.fr/display/FOR/Curseur+-+CSS
FOR-724 : https://jira.support-ent.fr/browse/FOR-724
=> fix(cursor): [#FOR-724] adapt cursor display to size number

common/src/main/resources/ts/services/FormService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/FolderController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/service/RelFormFolderService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultRelFormFolderService.java
We have removed unused api forms/multiple and its associated method createMultiple in formService
[FOR-752](https://jira.support-ent.fr/browse/FOR-752)
=> fix(api): #FOR-752 remove unused api forms/multiple

formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer/question-type-singleanswer.html
When form elements positions are wrong (ex : [1,2,4,5,8,11] when should be [1,2,3,4,5,6]) we recalculate them and save it, fixing the wrong position value stored in BDD.
FOR-755 : https://jira.support-ent.fr/browse/FOR-755
=> fix(position): [#FOR-755] fix form elements positions when going rogue

formulaire/src/main/resources/public/sass/global/_formulaire.scss
Fix filters color
FOR-754 : https://jira.support-ent.fr/browse/FOR-754
=> fix(css): [#FOR-754] fix filters color

formulaire/src/main/resources/public/ts/directives/formulaire-picker-file/formulaire-picker-file.directive.ts
Fix drop files in import ZIP forms pop-up
FOR-756 : https://jira.support-ent.fr/browse/FOR-756
=> fix(import): [#FOR-756] fix import ZIP drop file

common/src/main/java/fr/openent/form/core/constants/DateFormats.java, common/src/main/java/fr/openent/form/core/models/Form.java, common/src/main/java/fr/openent/form/helpers/DateHelper.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/service/FormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
Fixing some issues when trying to iterate through a jsonArray which contains a list of Models due to a modification of listByIds method in july. The consequence was a server exception error.
We change the way to iterate through this List of Models Form to set a property.
Also we modify the method updateMultiple in service to fit with the models and return a future <JsonArray> if succeed.
Try to delete a form and then to restore it
[FOR-753](https://jira.support-ent.fr/browse/FOR-753)
=> fix(restore): #FOR-753 update controller and service with the use of Form Models instead of jsonObjects

common/src/main/resources/ts/models/FormElement/Section.ts
A section targetting the default next element is now able to update when creating element after
FOR-762 : https://jira.support-ent.fr/browse/FOR-762
=> fix(targetting): [#FOR-762] fix next default target for section

formulaire/src/main/resources/public/sass/global/_formulaire.scss
Fix the fact that when clicking on a question its status goes from disabled to editable (in form-editor)
FOR-763 : https://jira.support-ent.fr/browse/FOR-763
=> fix(click): [#FOR-763] fix question edition on click

formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts
When skipping a conditional question the next button is now able to click.
FOR-764 : https://jira.support-ent.fr/browse/FOR-764
=> fix(conditional): [#FOR-764] fix form public response to conditional question

formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json
For greater clarity we have renamed “matrix cases à cocher” by “multiple à choix multiple”. To standardize the module we have also put all “choix multiples” in the singular.
Create a matrix type question, in the drop-down list you should now have "question à choix unique", and "question à choix multiple"
[FOR-766](https://jira.support-ent.fr/browse/FOR-766)
=> fix(question-type-matrix): #FOR-766 changing a question title

formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.html
Fix custom_answer for choices in singleanswerradio questions
FOR-767 : https://jira.support-ent.fr/browse/FOR-767
=> fix(choice): [#FOR-767] fix custom_answer for singleanswerradio questions

common/src/main/resources/ts/models/QuestionChoice.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer/question-type-singleanswer.directive.ts
A question targetting the default next element is now able to update when creating element after
Create a form with at least one conditionnal question. You should see only "accéder au récapitulatif des réponses (fin du formulaire)" ; then add an other question or section, targetting should be updating with "accéder à la question/section suivante"
[FOR-769](https://jira.support-ent.fr/browse/FOR-769)
=> fix(targetting): #FOR-769 fix next default target for question

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
We recalculate section_position and save them if there was some inconsistency
FOR-770 : https://jira.support-ent.fr/browse/FOR-770
=> fix(section_position): [#FOR-770] fix section_positions when going rogue

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
Add verification to apply fix only to questions inside a section, not form elements questions
FOR-770 : https://jira.support-ent.fr/browse/FOR-770
=> fix(section_position): [#FOR-770] fix section_position only for questions in section

formulaire-public/src/main/resources/public/ts/directives/public-respond-question-item/public-respond-question-item.html
Fix custom_answer for choices in singleanswerradio question public side
[FOR-767](https://jira.support-ent.fr/browse/FOR-767)
=> fix(public-respond-question-item): #FOR-767 fix custom_answer for singleanswerradio questions

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
Avoid multiple saving at same time in edition view.
FOR-777 : https://jira.support-ent.fr/browse/FOR-777
=> fix(saving): [#FOR-777] avoid multiple saving at same time in edition view

common/src/main/resources/ts/utils/utils.ts, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
Check if choice positions are really following an order like [1,2,3,4] instead of [2,1,3,4] or [1,3,3,4] for instance (wron order, doubles, etc.)
FOR-775 : https://jira.support-ent.fr/browse/FOR-775
=> fix(saving): [#FOR-775] fix choice positions when going rogue

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/models/Response.java, common/src/main/resources/ts/core/constants/fields.ts, common/src/main/resources/ts/models/Response.ts, common/src/main/resources/ts/services/ResponseService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java, formulaire/src/main/java/fr/openent/formulaire/security/CustomShareAndOwner.java, formulaire/src/main/java/fr/openent/formulaire/service/ResponseService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultResponseService.java, formulaire/src/main/resources/public/template/containers/respond-question.html, formulaire/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.directive.ts
Before my changes each question were asking their responses to the API, resulting in a lot of API calls. Now the controller make all thoses calls at once in give the data to the questions
Documention API : https://confluence.support-ent.fr/display/FOR/Response#operations-tag-default
Create a form, add questions, respond to the form and check if the responses are saved across the page of the form, when you refresh, and at the recap on the end on the form.
You can also check if form preview in form editor work well and save responses across pages
[FOR-789](https://jira.support-ent.fr/browse/FOR-789)
=> fix(optimisation): [#FOR-789] fix responses API call optimisation

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/models/Distribution.java, common/src/main/java/fr/openent/form/core/models/FilePayload.java, common/src/main/java/fr/openent/form/core/models/Response.java, formulaire/src/main/java/fr/openent/formulaire/controllers/DistributionController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseFileController.java, formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java, formulaire/src/main/java/fr/openent/formulaire/security/CustomShareAndOwner.java, formulaire/src/main/java/fr/openent/formulaire/service/DistributionService.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionChoiceService.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionService.java, formulaire/src/main/java/fr/openent/formulaire/service/ResponseService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultDistributionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionChoiceService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultResponseService.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultDistributionServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionChoiceServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultResponseServiceTest.java
Add multiple API endpoints for ResponseController.
Also improve some naming or variables' types.
Documentation :
- https://confluence.support-ent.fr/display/FOR/Response#operations-tag-default
- https://confluence.support-ent.fr/display/FOR/Response+File#operations-tag-default
FOR-788 : https://jira.support-ent.fr/browse/FOR-788
=> feat(response): [#FOR-788] create new response API endpoints

common/src/main/resources/ts/models/FormElement/Section.ts, common/src/main/resources/ts/models/QuestionChoice.ts
Fix saving of targets for sections in editor view
FOR-791 : https://jira.support-ent.fr/browse/FOR-791
=> fix(targeting): [#FOR-791] fix saving targets in editor view

formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts
Fix selection of the next element (target) according to the user response
FOR-792 : https://jira.support-ent.fr/browse/FOR-792
=> fix(response): [#FOR-792] fix targeting system in responses views

formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
When responding to a question with multiple choices, if you unchecked a choice, went to a next question and go back it was still checked. We fixed it.
FOR-795 : https://jira.support-ent.fr/browse/FOR-795
=> fix(response): [#FOR-795] fix choice deletion when responding

common/src/main/resources/ts/models/Files.ts, common/src/main/resources/ts/services/ResponseFileService.ts, common/src/main/resources/ts/services/ResponseService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseFileController.java, formulaire/src/main/java/fr/openent/formulaire/security/CustomShareAndOwner.java, formulaire/src/main/resources/public/ts/controllers/respond-question.ts
Fix saving errors when responding to a type file question
Documentation : 
- https://confluence.support-ent.fr/display/FOR/Response#operations-tag-default
- https://confluence.support-ent.fr/display/FOR/Response+File#operations-tag-default
FOr-797 : https://jira.support-ent.fr/browse/FOR-797
=> fix(files): [#FOR-797] fix files responses

formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java, formulaire/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/directives/question/respond-matrix/respond-matrix.directive.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.directive.ts
Fix saving matrix responses
FOR-798 : https://jira.support-ent.fr/browse/FOR-798
=> fix(matrix): [#FOR-798] fix matrix responses

common/src/main/resources/ts/models/FormElement/FormElement.ts, common/src/main/resources/ts/utils/formElement.ts
We added some checks to avoid undefined values in progress-bar calculations
FOR-811 : https://jira.support-ent.fr/browse/FOR-811
=> fix(progress-bar): [#FOR-811] fix progress-bar

formulaire/src/main/java/fr/openent/formulaire/export/FormResponsesExportPDF.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultResponseService.java
We changed our SQL request to avoid having lines in data with null answer. This was caused by LEFT JOIN and wrong data.
We used INNER JOIN instead to avoid the problem in case we still have wrong data in the future.
FOR-813 : https://jira.support-ent.fr/browse/FOR-813
=> fix(pdf): [#FOR-813] fix export PDF SQL request

common/src/main/resources/ts/directives/rgpd.ts
Fix scope of rgpd directive
FOR-819 : https://jira.support-ent.fr/browse/FOR-819
=> fix(rgpd): [#FOR-819] fix RGPD text display

common/src/main/resources/ts/models/FormElement/Section.ts, common/src/main/resources/ts/services/FormElement/QuestionService.ts, common/src/main/resources/ts/services/FormElement/SectionService.ts, common/src/main/resources/ts/services/QuestionChoiceService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionChoiceController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java, formulaire/src/main/java/fr/openent/formulaire/security/CustomShareAndOwner.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionChoiceService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionChoiceService.java, formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/section-item/section-item.directive.ts, formulaire/src/main/resources/public/ts/directives/section-item/section-item.html, formulaire/src/main/resources/sql/029-add-sharing-rights.sql
Now we can duplicate a section with all the questions inside when creating a form
Documentation API : 
- https://confluence.support-ent.fr/display/FOR/Question+Choice
- https://confluence.support-ent.fr/display/FOR/Question
FOR-547 : https://jira.support-ent.fr/browse/FOR-547
=> feat(section): [#FOR-547] allow duplication of a section

formulaire-public/src/main/resources/public/ts/directives/public-respond-question-item/public-respond-question-item.directive.ts
When going from a question to the next in a public form we now detect the change with $onChange() function and we are therefore able to init the data correctly
FOR-818 : https://jira.support-ent.fr/browse/FOR-818
=> fix(apply): [#FOR-818] fix respond-question apply for public-forms

common/src/main/java/fr/openent/form/core/constants/DateFormats.java, common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/models/Form.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
Fix public_key setting when updating a form. It needed to cast the form as JsonObject correctly to do so.
FOR-750 : https://jira.support-ent.fr/browse/FOR-750
=> fix(update): [#FOR-750] fix form public_key on update

formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/template/containers/prop-form.html, formulaire/src/main/resources/public/ts/controllers/form-prop.ts
Public warnings now only appears when form is already existing, private and you check the "public" property
FOr-750 : https://jira.support-ent.fr/browse/FOR-750
=> fix(public): [#FOR-750] improve display public warnings

formulaire-public/src/main/resources/public/ts/directives/public-respond-question-item/public-respond-question-item.directive.ts
When responding a public form, we fixed switch between custom answer and classical ones
FOR-827 : https://jira.support-ent.fr/browse/FOR-827
=> fix(custom_answer): [#FOR-827] fix custom_answer in public form

common/src/main/java/fr/openent/form/core/models/Form.java, formulaire/src/main/resources/public/ts/controllers/form-prop.ts
When using toJson() on a Form in Java, it was only applying a toString() function for a Date.
But Date.toString() gives a "EEE MMM dd HH:mm:ss z yyyy" formatted string.
So now we format it to keep a date in "yyyy-MM-dd'T'HH:mm:ss.SSS" format instead.
FOr-833 : https://jira.support-ent.fr/browse/FOR-833
=> fix(dates): [#FOR-833] fix form dates formatting

formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
- when duplicating section we save question currently being edited
- we changed some text
FOR-547 : https://jira.support-ent.fr/browse/FOR-547
=> fix(duplication): [#FOR-547, #FOR-750] fix question saving in section duplication

formulaire/src/main/resources/sql/031-add-sharing-rights.sql
Add missing sharing rights
FOR-820 : https://jira.support-ent.fr/browse/FOR-820
=> fix(rights): [#FOR-820] fix sharing rights

formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts
Add verification in signleanswer response for public forms to avoid wrongly implemented answered
FOr-827 : https://jira.support-ent.fr/browse/FOR-827
=> fix(results): [#FOR-827] fix custom answer results for singleanswer

.github/workflows/dev-check-repository.yml, formulaire-public/deployment/formulaire-public/conf.json.template, formulaire/deployment/formulaire/conf.json.template
Changes versions for deployment & gitlab CI/CD instructions
https://jira.support-ent.fr/browse/FOR-856
=> fix(migration): #FOR-856 fix versions & git instructions for vertx

formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/service/FormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFormServiceTest.java
When updating a public form, the sharing link is now constant where it was regenerated each time before.
FOR-852 : https://jira.support-ent.fr/browse/FOR-852
=> fix(update): [FOR-852] fix update formulaire publics

formulaire/src/main/java/fr/openent/formulaire/helpers/upload_file/FileHelper.java
Modification d'une fonction non utilisée en Vert.x 4.5 qui empêche l'import d'un fichier ZIP
https://jira.support-ent.fr/browse/FOR-856
=> fix(upload): #FOR-856 fix upload zip file function

formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java
When sending a reminder to a number of people exactly equal to the conf propertie `zimbra-max-recipients`, a bug was sending the given notification as many times the number of people in the list.
For instance, if the config is set to `50` and I sent my reminder to `50` people exactly, they'll all receive `50` notifications instead of one.
This is now fixed.
More infos about the bug here : https://confluence.support-ent.fr/display/FOR/MO-485
FOR-859 : https://jira.support-ent.fr/browse/FOR-859
=> fix(reminder): [#FOR-859] fix duplication of notifs when remind is send

formulaire-public/src/main/resources/public/ts/directives/public-recap-question-item/public-recap-question-item.html, formulaire-public/src/main/resources/public/ts/directives/public-respond-question-item/public-respond-question-item.html, formulaire/src/main/resources/public/sass/global/components/_respond-question.scss, formulaire/src/main/resources/public/ts/directives/question/recap-question-item/recap-question-item.html, formulaire/src/main/resources/public/ts/directives/question/respond-question-item/respond-question-item.html
Added a CSS class to some HTML div to avoid conflict between two CSS class existing (one was trigger when shouldn't have)
FOR-858 : https://jira.support-ent.fr/browse/FOR-858
=> fix(): [#FOR-858] fix image size in freetext

formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/question-types/question-type-matrix/question-type-matrix.directive.ts
Fiw beheviours when creating a matrix :
- creation
- move
- deletion
To do that we fix a function called everywhere which was modifing an object instead of only reading it.
FOR-855 : https://jira.support-ent.fr/browse/FOR-855
=> fix(): [#FOR-855] fix behaviours on matrix lines in creation mode

formulaire/frontend/src/containers/FolderModal/index.tsx, formulaire/frontend/src/containers/FolderModal/style.ts, formulaire/frontend/src/containers/FolderModal/types.ts, formulaire/frontend/src/core/enums.ts, formulaire/frontend/src/core/models/folders/types.ts, formulaire/frontend/src/core/style/boxStyles.ts, formulaire/frontend/src/core/style/modalStyle.ts, formulaire/frontend/src/providers/HomeProvider/index.tsx, formulaire/frontend/src/providers/HomeProvider/types.ts, formulaire/frontend/src/providers/HomeProvider/utils.ts, formulaire/frontend/src/routes/home/index.tsx, formulaire/frontend/src/services/api/services/folderApi.ts, formulaire/frontend/src/types.ts
**New FolderModal Component:**
Introduces the FolderModal component to handle folder creation and renaming with integrated state management and event handling.
**API Updates:**
Updates the folder API services to use new payload types (CreateFolderPayload and UpdateFolderPayload).
**New Types & Styles:**
Adds component-specific types (e.g., FolderModalProps, FolderModalMode) and updates modal styles for layout and action buttons.
[FOR-886](https://jira.support-ent.fr/browse/FOR-886)
=> feat(modal): #FOR-886 add create/rename folder modal in homepage

formulaire/frontend/package.json, formulaire/frontend/src/components/HomeTab/index.tsx, formulaire/frontend/src/components/HomeTab/types.ts, formulaire/frontend/src/containers/FolderModal/index.tsx, formulaire/frontend/src/containers/HomeMainLayout/index.tsx, formulaire/frontend/src/containers/HomeMainLayout/styles.ts, formulaire/frontend/src/containers/HomeMainLayout/types.ts, formulaire/frontend/src/containers/HomeSidebar/index.tsx, formulaire/frontend/src/containers/HomeSidebar/style.ts, formulaire/frontend/src/containers/HomeSidebar/utils.ts, formulaire/frontend/src/containers/HomeView/HomeView.tsx, formulaire/frontend/src/containers/HomeView/utils.ts, formulaire/frontend/src/core/enums.ts, formulaire/frontend/src/core/models/folders/types.ts, formulaire/frontend/src/providers/HomeProvider/enums.ts, formulaire/frontend/src/providers/HomeProvider/index.tsx, formulaire/frontend/src/providers/HomeProvider/types.ts, formulaire/frontend/src/providers/HomeProvider/utils.ts, formulaire/frontend/src/services/api/services/folderApi.ts, formulaire/frontend/src/styles/global.ts
=> feat(sidebar) : mainlayout + sidebarlayout + treeview-impl + tab

formulaire/frontend/src/containers/DeleteModal/index.tsx, formulaire/frontend/src/containers/FolderModal/index.tsx, formulaire/frontend/src/containers/FormImportModal/index.tsx, formulaire/frontend/src/containers/HomeSidebar/utils.ts, formulaire/frontend/src/containers/HomeView/enums.ts, formulaire/frontend/src/containers/HomeView/useMapToasterButtons.ts, formulaire/frontend/src/core/constants.ts, formulaire/frontend/src/providers/HomeProvider/index.tsx, formulaire/frontend/src/providers/HomeProvider/types.ts, formulaire/frontend/src/services/api/services/formulaireApi/formApi.ts
=> feat(deletemodal): implement archive and restore action

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/models/Form.java, formulaire/backend/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/backend/src/main/java/fr/openent/formulaire/service/impl/ImportExportService.java, formulaire/backend/src/main/resources/sql/032-add-columns-to-form.sql, formulaire/backend/src/test/java/fr/openent/formulaire/service/DefaultFormServiceTest.java
- allow backend to deal with new form fields : description & is_progrss_bar_displayed
FOR-699 : https://jira.support-ent.fr/browse/FOR-699
FOR-596 : https://jira.support-ent.fr/browse/FOR-596
=> feat(): [#FOR-699, #FOR-596] add description and isProgressBArDisplayed to form props

formulaire/backend/src/main/resources/i18n/en.json, formulaire/backend/src/main/resources/i18n/fr.json, formulaire/frontend/src/containers/DeleteModal/index.tsx, formulaire/frontend/src/containers/FormImportModal/index.tsx, formulaire/frontend/src/containers/FormPropModal/index.tsx, formulaire/frontend/src/containers/HomeSidebar/index.tsx, formulaire/frontend/src/core/models/form/types.ts, formulaire/frontend/src/core/models/form/utils.ts, formulaire/frontend/src/main.tsx, formulaire/frontend/src/services/api/services/archiveApi/importExportApi.ts, formulaire/frontend/src/services/api/services/formulaireApi/folderApi.ts, formulaire/frontend/src/services/api/services/formulaireApi/formApi.ts
add success and error toast for all currents api calls.
fix some inputvalues in formPropModal
disable createFolder Button when in shared and trash folder
=> feat(toast): add toasts + some ui fixes

common/src/main/java/fr/openent/form/core/constants/ConfigFields.java, formulaire/backend/deployment/formulaire/conf.json.template, formulaire/backend/src/main/java/fr/openent/formulaire/controllers/FormulaireController.java, formulaire/frontend/index.html
=> core(conf): add host & theme conf to front

formulaire/frontend/src/components/Toaster/index.tsx, formulaire/frontend/src/components/Toaster/style.ts, formulaire/frontend/src/containers/FormPropModal/index.tsx, formulaire/frontend/src/containers/FormPropModal/style.ts, formulaire/frontend/src/containers/HomeMainLayout/styles.ts, formulaire/frontend/src/containers/HomeSidebar/index.tsx, formulaire/frontend/src/core/constants.ts, formulaire/frontend/src/hook/useFormatDateWithTime.ts
Here is the summary of changes between the `dev-react` and `tsev-fix` branches:
1. **Toaster Component**
- **File:** `formulaire/frontend/src/components/Toaster/index.tsx`
- Replaced imports from `@mui/material` with `@cgi-learning-hub/ui`.
- Added and applied `toasterButtonStyle` for button components.
- **File:** `formulaire/frontend/src/components/Toaster/style.ts`
- Added new style `toasterButtonStyle` for button hover and active states.
2. **FormPropModal Component**
- **File:** `formulaire/frontend/src/containers/FormPropModal/index.tsx`
- Removed `variant={TypographyVariant.H4}` from `Typography` components.
- Added `slotProps` for error handling in `DatePicker`.
- Adjusted `maxWidth` for a `TextField`.
- Added style `subContentColumnWrapper` to an additional `Box`.
- **File:** …
=> fix minor changes

formulaire/frontend/src/common/ShareModal/ShareBookmarkLine.tsx, formulaire/frontend/src/common/ShareModal/ShareModal.tsx, formulaire/frontend/src/components/DistributionTable/index.tsx, formulaire/frontend/src/components/ImagePickerMediaLibrary/index.tsx, formulaire/frontend/src/containers/HomeMainLayout/index.tsx, formulaire/frontend/src/containers/HomeView/index.tsx, formulaire/frontend/src/containers/HomeView/useMapToasterButtons.ts, formulaire/frontend/src/containers/MyAnswersModal/index.tsx, formulaire/frontend/src/core/enums.ts, formulaire/frontend/src/core/models/form/utils.ts, formulaire/frontend/src/core/style/themeProps.ts, formulaire/frontend/src/hook/useFormatDateWithTime.ts, formulaire/frontend/src/providers/ModalProvider/types.ts, formulaire/frontend/src/providers/ModalProvider/utils.ts
=> feat(answers): FOR-#954 add sent forms my answers modal

formulaire/frontend/src/components/Breadcrumbs/index.tsx, formulaire/frontend/src/components/Breadcrumbs/style.ts, formulaire/frontend/src/components/Breadcrumbs/types.ts, formulaire/frontend/src/components/DraggableFolder/style.ts, formulaire/frontend/src/components/Header/index.tsx, formulaire/frontend/src/components/Header/style.ts, formulaire/frontend/src/components/OrganizeFilter/index.tsx, formulaire/frontend/src/components/OrganizeFilter/style.ts, formulaire/frontend/src/containers/FolderModal/index.tsx, formulaire/frontend/src/containers/FormPropModal/index.tsx, formulaire/frontend/src/containers/FormPropModal/style.ts, formulaire/frontend/src/containers/HomeMainFolders/index.tsx, formulaire/frontend/src/containers/HomeMainForms/index.tsx, formulaire/frontend/src/containers/HomeMainLayout/index.tsx, formulaire/frontend/src/containers/HomeMainLayout/style.ts, formulaire/frontend/src/core/enums.ts, formulaire/frontend/src/core/models/folder/types.ts, formulaire/frontend/src/core/style/boxStyles.ts, formulaire/frontend/src/core/style/dndStyle.ts, formulaire/frontend/src/core/utils.ts, formulaire/frontend/src/providers/HomeProvider/utils.ts
- fix alignments between elements
- fix size and alignment of empty state view
- fix icons display in breadcrumbs
- fix minor others errors (text size, color, spacing etc.)
- fiw some linter errors
FOR-875 : https://jira.support-ent.fr/browse/FOR-875
FOR-876 : https://jira.support-ent.fr/browse/FOR-876
FOR-879 : https://jira.support-ent.fr/browse/FOR-879
=> fix(): improve design and behaviors

.gitignore, README.md, build.sh, build.sh.bkp, docker-compose.yml, formulaire-public/angular/build.sh, formulaire-public/angular/docker-compose.yml, formulaire-public/frontend/build.sh, formulaire-public/frontend/docker-compose.yml, formulaire/angular/build.sh, formulaire/angular/docker-compose.yml, formulaire/frontend/build.sh, formulaire/frontend/docker-compose.yml
=> chore(): change build logic

README.md, common/src/main/java/fr/openent/form/core/constants/ConfigFields.java, common/src/main/java/fr/openent/form/helpers/LogHelper.java, formulaire/backend/deployment/formulaire/conf.json.template, formulaire/backend/src/main/java/fr/openent/formulaire/cron/NotifyCron.java, formulaire/backend/src/main/java/fr/openent/formulaire/service/FormService.java, formulaire/backend/src/main/java/fr/openent/formulaire/service/NotifyService.java, formulaire/backend/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/backend/src/main/java/fr/openent/formulaire/service/impl/DefaultNotifyService.java, formulaire/backend/src/main/resources/i18n/timeline/en.json, formulaire/backend/src/main/resources/i18n/timeline/fr.json, formulaire/backend/src/main/resources/view-src/notify/closing_form_notification.html, formulaire/backend/src/main/resources/view-src/notify/closing_form_notification.json
Use an existing CRON to send a new type of notification.
These notifications inform the users of forms closing soon, encouraging them to respond before the deadline.
FOR-566 : https://jira.support-ent.fr/browse/FOR-566
=> feat(closingCron): [#FOR-566] add a new CRON to notify user of form closing soon

formulaire/frontend/src/containers/HomeMainTable/index.tsx
=> fix(): fix table icon tooltip and answers css

.github/workflows/dev-check-repository.yml, formulaire/frontend/build.sh, formulaire/frontend/src/components/HomeTab/index.tsx, formulaire/frontend/src/containers/HomeSidebar/index.tsx, formulaire/frontend/src/core/rights.ts, formulaire/frontend/src/core/utils.ts, formulaire/frontend/src/providers/HomeProvider/index.tsx, formulaire/frontend/src/providers/HomeProvider/types.ts, formulaire/frontend/src/providers/HomeProvider/utils.ts
Take into account the user workflow rights to display or redirect on the correct hom tab page
=> fix(tab): display tabs according to workflow rights

formulaire/frontend/src/components/ActionBar/index.tsx, formulaire/frontend/src/components/ActionBar/style.ts, formulaire/frontend/src/components/ActionBar/types.ts, formulaire/frontend/src/components/SentForm/index.tsx, formulaire/frontend/src/components/Toaster/types.ts, formulaire/frontend/src/containers/HomeMainFormsTable/index.tsx, formulaire/frontend/src/containers/HomeView/enums.ts, formulaire/frontend/src/containers/HomeView/index.tsx, formulaire/frontend/src/containers/HomeView/types.ts, formulaire/frontend/src/containers/HomeView/useMapActionBarButtons.ts, formulaire/frontend/src/core/pathHelper.ts, formulaire/frontend/src/providers/HomeProvider/index.tsx, formulaire/frontend/src/providers/HomeProvider/types.ts
- rename Toaster by ActionBar and same goes for all the related code
- add button "Result" to the ActionBar
=> fix(): fix minor bugs

formulaire/frontend/src/common/ShareModal/ShareBookmarkLine.tsx, formulaire/frontend/src/common/ShareModal/ShareModal.tsx, formulaire/frontend/src/common/ShareModal/utils.ts, formulaire/frontend/src/common/ShareModal/utils/showShareRightLine.ts
- display public link in ShareModal
=> fix(): add public link in share modal

formulaire/frontend/src/components/AnswerMainLayout/index.tsx, formulaire/frontend/src/components/AnswerMainLayout/style.ts
This pull request refactors the `AnswerMainLayout` component in `formulaire/frontend` by updating styles and improving code organization.
[FOR-954](https://jira.support-ent.fr/browse/FOR-954)
=> fix(return): #FOR-954 fix tabs moving between tab

formulaire/frontend/src/common/ShareModal/ShareModal.tsx, formulaire/frontend/src/common/ShareModal/utils.ts, formulaire/frontend/src/core/constants.ts
This pull request introduces enhancements to the `ShareModal` component in the `formulaire` frontend, focusing on improving internationalization, refining public link generation, and adding conditional rendering for public link visibility. 
[FOR-878](https://jira.support-ent.fr/browse/FOR-878)
=> fix(return): #FOR-878 fix public link when form not public

formulaire/backend/src/main/resources/i18n/fr.json, formulaire/frontend/src/components/DistributionTable/index.tsx, formulaire/frontend/src/containers/RemindModal/index.tsx, formulaire/frontend/src/containers/RemindModal/style.ts, formulaire/frontend/src/containers/RemindModal/utils.ts
This pull request includes updates to improve the user interface, functionality, and localization of the `formulaire` project. Key changes include adjustments to the table layout, enhancements to the `RemindModal` component, and corrections to French translations.
[FOR-880](https://jira.support-ent.fr/browse/FOR-880)
=> fix(return): #FOR-880 fix remind modal return

formulaire/backend/src/main/resources/i18n/en.json, formulaire/backend/src/main/resources/i18n/fr.json, formulaire/frontend/src/components/AnswerMainLayout/style.ts, formulaire/frontend/src/containers/HomeSidebar/index.tsx, formulaire/frontend/src/containers/RemindModal/style.ts
Few style changes on remind modal and tabs selector, i18n on export modal
=> fix(return) : fix return for remind modal, export modal, tabs

formulaire/backend/src/main/resources/i18n/en.json, formulaire/backend/src/main/resources/i18n/fr.json, formulaire/frontend/src/components/CreationEditingSection/index.tsx, formulaire/frontend/src/components/CreationSection/index.tsx, formulaire/frontend/src/containers/CreationSectionWrapper/index.tsx, formulaire/frontend/src/providers/CreationProvider/index.tsx, formulaire/frontend/src/providers/CreationProvider/types.ts, formulaire/frontend/src/services/api/services/formulaireApi/sectionApi.ts
* **Default Section Title**
– Added “Section title” (EN) / “Titre de la section” (FR) to i18n.
* **Modal Refactoring**
– Moved `CreateFormElementModal` into `CreationSectionWrapper` only when its `questionModalSection` matches.
– Introduced `questionModalSection` state in `CreationProvider` for tracking.
* **API-backed Section Creation**
– Switched to `useCreateSectionMutation` when adding questions to new sections.
– Enhanced `sectionApi` to apply `transformSection` to creation responses.
* **Minor Tweaks**
– Made `handleAddNewQuestion` async for proper section handling.
[FOR-702](https://jira.support-ent.fr/browse/FOR-702)
=> feat(section): #FOR-702 add question at section's creation

formulaire/frontend/src/components/CreationQuestionTypes/CreationQuestionChoice/enum.ts, formulaire/frontend/src/components/CreationQuestionTypes/CreationQuestionChoice/index.tsx, formulaire/frontend/src/components/CreationQuestionTypes/CreationQuestionChoice/style.ts, formulaire/frontend/src/components/CreationQuestionTypes/CreationQuestionChoice/types.ts, formulaire/frontend/src/containers/CreationLayout/index.tsx, formulaire/frontend/src/containers/CreationQuestionChoiceWrapper/index.tsx, formulaire/frontend/src/containers/CreationQuestionChoiceWrapper/style.ts, formulaire/frontend/src/containers/CreationQuestionChoiceWrapper/types.ts, formulaire/frontend/src/containers/CreationQuestionChoiceWrapper/useChoiceActions.ts, formulaire/frontend/src/containers/CreationQuestionWrapper/utils.tsx
This PR enhances the form creation interface with image support and improved styling for question choices.
* Added `CreationQuestionChoiceType` enum (`DROPDOWN`, `SINGLE_CHOICE`, `MULTIPLE_CHOICE`).
* Refactored `CreationQuestionChoice` to handle images and type-specific icons.
* Introduced `updateChoiceImage` function for image management.
* Updated styles for better layout and media integration.
* Modified wrappers and utils to support the new component and type handling.
These updates improve flexibility and visual quality when editing question choices.
=> feat(choice): #FOR-909 add question choice

formulaire/frontend/src/containers/RemindModal/index.tsx
Add a default subject to the mail send from remind modal
FOR-976 : https://jira.support-ent.fr/browse/FOR-976
=> fix(remind): [#FOR-976] add default subject in remind mail

formulaire/frontend/src/containers/FormPropModal/index.tsx
When a form has 1 or more response the following checkbox will be disabled : "Permettre plusieurs réponses d'un même utilisateur", "Anonymiser les réponses" and "Collecte de données à caractère personne"
[FOR-975](https://jira.support-ent.fr/browse/FOR-975)
=> fix(form): #FOR-975 fix checkbox not disabled for form with 1+ answer

formulaire/frontend/src/providers/HomeProvider/index.tsx
On the page displaying the forms to respond, we now hide the one archived by the owners
FOR-983 : https://jira.support-ent.fr/browse/FOR-983
=> fix(): [#FOR-983] fix display forms for responders

formulaire/frontend/src/i18n.ts
Format i18n to match choosen interpolation.
It allows to fix all the i18n interpolated texts fetched from Edifice like the username in the header with 1D theme
FOR-972 : https://jira.support-ent.fr/browse/FOR-972
=> fix(1D): [#FOR-972] fix username in header whith 1D thme

formulaire/frontend/src/components/QuestionChoicesUpDownButtons/index.tsx, formulaire/frontend/src/components/QuestionChoicesUpDownButtons/types.ts, formulaire/frontend/src/containers/CreationQuestionChoiceWrapper/index.tsx, formulaire/frontend/src/containers/CreationQuestionChoiceWrapper/style.ts, formulaire/frontend/src/containers/CreationQuestionChoiceWrapper/useChoiceActions.ts, formulaire/frontend/src/containers/CreationQuestionChoiceWrapper/utils.ts
New choice now trigger on blur and not on click 
[FOR-909](https://jira.support-ent.fr/browse/FOR-909)
=> fix(choice): #FOR-909 fix new choice mecanism

formulaire/frontend/src/components/CreationQuestionTypes/CreationQuestionChoice/index.tsx, formulaire/frontend/src/components/CreationQuestionTypes/CreationQuestionFreetext/style.ts, formulaire/frontend/src/containers/CreationLayout/index.tsx, formulaire/frontend/src/containers/CreationQuestionChoiceWrapper/index.tsx, formulaire/frontend/src/containers/CreationQuestionChoiceWrapper/utils.ts, formulaire/frontend/src/containers/CreationQuestionWrapper/utils.tsx
added ranking question support 
[FOR-906](https://jira.support-ent.fr/browse/FOR-906)
=> feat(choice): #FOR-906 add ranking question

formulaire/frontend/src/containers/CreationMatrixChildrenWrapper/index.tsx, formulaire/frontend/src/containers/CreationQuestionChoiceWrapper/index.tsx, formulaire/frontend/src/core/utils.ts
Using "Enter" or "Shift+Enter" allows to save the choice and move up or down according to the combo
FOR-759 : https://jira.support-ent.fr/browse/FOR-759
=> feat(): [#FOR-759] improve behaviours on question choice
