common/src/main/java/fr/openent/form/core/constants/Field.java, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java
For an unknown reason, duplicate responses appear in the database.
The goal here is to prevent the creation of the response if database already contains identical ones.
FOR-415 : https://jira.support-ent.fr/browse/FOR-415
=> fix: [FOR-415] Avoid creation of duplicate responses

formulaire/src/main/resources/public/sass/global/_formulaire.scss, formulaire/src/main/resources/public/sass/global/components/_edit-form.scss, formulaire/src/main/resources/public/ts/directives/question/question-item.ts
When at least one person has responded to the form we block the posibility to use the switches on edit questions.
We also changed the design to make them look like disabled in this situation.
FOR-417 : https://jira.support-ent.fr/browse/FOR-417
=> fix(css): [FOR-417] Disable switches on edit questions when there are already responses

formulaire/src/main/resources/public/template/lightbox/form-sharing.html, formulaire/src/main/resources/public/ts/controllers/forms-list.ts
Check if sharePanel close confirmation pop up is open and if it is we do not show the public link and its button.
FOR-426 : https://jira.support-ent.fr/browse/FOR-426
=> fix(sharePanel): [FOR-426] hide public link on sharing close confirmation pop up

formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/section-item.ts
We change the saving behaviour of questions on edit-form page :
- we do not block saving of questions without title anymore
- we hide edit section icon when editing another element
- we improve saving and non-saving area behaviours
FOR-396 : https://jira.support-ent.fr/browse/FOR-396
=> fix: [FOR-396] fix saving behaviour on edit-form page

common/src/main/resources/ts/utils/formElement.ts, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
An old problem on form edition was the apparition of a "phantom question", a kind of question duplicated but not really existing (disapear on refresh). It was happenning when drag and drop a question from a section outside of it.
A fix was made to delete this unwanted effect.
But since a fix was made on the drag and drop this effect doesn't happen anymore and the fix is now obsolete and created another problem.
So here, we removed that obsolete fix.
FOR-431 : https://jira.support-ent.fr/browse/FOR-431
=> fix(DnD): [FOR-431] remove clean residue (obsolete) on DnD question in edit-form

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
Fix initialisation of choices' positions.
By default 3 empty choices are displayed. If you fill the second one for instance and then save your question, your choice will registered with position equal to 2 when it should be 1 because it's the only valid choice (when we have at least one valid choice we stop displaying empty default choices).
FOR-464 : https://jira.support-ent.fr/browse/FOR-464
=> fix(position) : [FOR-464] fix initialisation of choices' positions

formulaire-public/src/main/resources/public/ts/directives/public-matrix.ts, formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts, formulaire/src/main/resources/public/ts/directives/question/recap-question-item.ts, formulaire/src/main/resources/public/ts/directives/question/respond-matrix.ts, formulaire/src/main/resources/public/ts/directives/question/result-question-item.ts
We want choices of questions and children of matrix to be ordered always in the same way.
Some parts of the code where not forcing this ordering in ng-repeat, now it's fixed.
FOR-475 : https://jira.support-ent.fr/browse/FOR-475
=> fix(order): [FOR-475] force order of choices and matrix children where not defined yet

formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultDistributionService.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultDistributionServiceTest.java
In result graph for multipleanswer the percentage were wrong on web but right on PDF export.
We corrected the SQL request who was call but returned duplicated data.
FOR-474 : https://jira.support-ent.fr/browse/FOR-474
=> fix(result): [FOR-474] fix percentage in multipleanswer result graph

formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts
With the response refacto, old Response are now Responses.
A Responses type has a list of Response in a property 'all'.
The call to this property was missing to work with the new version.
FOR-482 : https://jira.support-ent.fr/browse/FOR-482
=> fix(response): [FOR-482] fix get getting of element in Responses

common/src/main/resources/ts/services/DistributionService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/DistributionController.java
When accessing to response page by URL, we check that the distribution corresponding is matching the connected user.
It avoids wrong people to answer the form of someone else with their link.
FOR-510 : https://jira.support-ent.fr/browse/FOR-510
=> fix(response) : [#FOR-510] avoid responder to respond for someone else

common/src/main/java/fr/openent/form/core/constants/ConfigFields.java, common/src/main/java/fr/openent/form/core/constants/Fields.java, formulaire/deployment/formulaire/conf.json.template, formulaire/src/main/java/fr/openent/formulaire/Formulaire.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/cron/NotifyCron.java, formulaire/src/main/java/fr/openent/formulaire/cron/RgpdCron.java, formulaire/src/main/java/fr/openent/formulaire/service/DistributionService.java, formulaire/src/main/java/fr/openent/formulaire/service/FormService.java, formulaire/src/main/java/fr/openent/formulaire/service/NotifyService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultDistributionService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultNotifyService.java, formulaire/src/main/resources/i18n/timeline/en.json, formulaire/src/main/resources/i18n/timeline/fr.json, formulaire/src/main/resources/view-src/notify/new_form_notification.html, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultDistributionServiceTest.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFormServiceTest.java
- block notifications when formulaire is sent before opening date
- new CRON starting every day at midnight and sending notifications for all the forms sent but having an opening date define to this day -> for example a form created and sent the 6th but having an opening date defined for the 8th will have notifications sent by the CRON the 8th at 00h00
- improve text and template of notifications
FOR-506 : https://jira.support-ent.fr/browse/FOR-506
=> fix(notification) : [#FOR-506] send notifications only when date_opening has passed

common/src/main/resources/ts/core/constants/date_formats.ts, common/src/main/resources/ts/core/constants/index.ts, common/src/main/resources/ts/services/FormService.ts
When sending a moment object to the back it converts timezone to UTC without timezone.
We changed the format in front to have the correct date in BDD
FOR-527 : https://jira.support-ent.fr/browse/FOR-527
=> fix(date_opening): [#FOR-527] fix dates format before sending to the back

common/src/main/resources/ts/services/DistributionService.ts, common/src/main/resources/ts/utils/utils.ts, formulaire/src/main/resources/public/ts/controllers/forms-list.ts
In the remind pop-up names and surnames are displayed in two different columns.
For people with more than one word names or surnames, the displayed information was incorrect, which is now fixed.
FOR-541 : https://jira.support-ent.fr/browse/FOR-541
=> fix(remind) : [#FOR-541] fix name displaying in remind pop-up

common/src/main/resources/ts/core/constants/constants.ts, common/src/main/resources/ts/utils/color.ts, common/src/main/resources/ts/utils/utils.ts
When using many choices for QCM for instance, the colors number was limited to 25. Now if you reach this number we empty the pool of colors and allow the reusing of the same colors for the same graph
FOR-538 : https://jira.support-ent.fr/browse/FOR-538
=> fix(colors) : [#FOR-538] fix colors displaying for great number of choices

formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts
When having several question cursor in the same form, the initial values were mixed.
Now we can save values, come back again and each cursor display its own value as expected.
FOR-544 : https://jira.support-ent.fr/browse/FOR-544
=> fix(cursor): [#FOR-544] fix initial value for cursor questions

formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire-public/src/main/resources/public/ts/directives/public-matrix.ts, formulaire-public/src/main/resources/public/ts/directives/public-question-item.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseController.java, formulaire/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/directives/question/respond-matrix.ts, formulaire/src/main/resources/public/ts/directives/question/respond-question-item.ts
For some types of question we added the possibility for the user to reset his response. It affects :
- Type DATE
- Type HOUR
- Type SINGLEANSWERRADIO
- Type MATRIX
La liste vm.responses.all n'est jamais vide dans ce composant, c'est pour ça qu'on utilise parfois des vm.responses.all[0] sans vérification préalable
FOR-513 : https://jira.support-ent.fr/browse/FOR-513
=> feat(response): [#FOR-513] allow to reset response for some question types

common/src/main/resources/ts/models/FormElement/Question.ts
Improve calculation of number of responses per choice for graph of questions with choices (unfinished responses were wrongly counted in PDF export)
FOR-564 : https://jira.support-ent.fr/browse/FOR-564
=> fix(graph): [#FOR-564] fix calcul nb responses per choice for graph with choices

common/src/main/resources/ts/utils/formElement.ts, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
When updating positions of form elements we now force to reset them from 1 to N according to their order, hence avoiding potential missing values
Example : a list of elements with positions [1,3,5,6,9] will be redefined with positions [1,2,3,4,5]
FOR-568 : https://jira.support-ent.fr/browse/FOR-568
=> fix(position): [#FOR-568] fix positions values (no missing values)

formulaire/src/main/java/fr/openent/formulaire/export/FormResponsesExportPDF.java
In front view, cursor average responses was rounded to 2 decimals. We did the same in export PDF.
- Export a PDF where the average is a double with many decimals (ex : 6.3333333333)
FOR-582 : https://jira.support-ent.fr/browse/FOR-582
=> fix(graph): [#FOR-582] round average value in export PDF

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/models/Form.java, common/src/main/java/fr/openent/form/core/models/Question.java, common/src/main/java/fr/openent/form/core/models/Section.java, common/src/main/resources/ts/models/FormElement/FormElement.ts, common/src/main/resources/ts/models/FormElement/FormElements.ts, common/src/main/resources/ts/models/FormElement/Section.ts, common/src/main/resources/ts/models/QuestionChoice.ts, common/src/main/resources/ts/utils/formElement.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/FormElementController.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionChoiceService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionChoiceService.java, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer/question-type-singleanswer.directive.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer/question-type-singleanswer.html, formulaire/src/main/resources/public/ts/directives/section-item/section-item.directive.ts, formulaire/src/main/resources/public/ts/directives/section-item/section-item.html, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultQuestionChoiceServiceTest.java
The previously implemented targetting system is know adapting when form elements are drag and drop from editor view or organization pop up
Play with drag and drop in editor view or organization pop up  and check that targetting values are still logic after each move
FOR-531 : https://jira.support-ent.fr/browse/FOR-531
=> fix(DnD): [#FOR-531] fix targetting system on drag and drop

formulaire/src/main/java/fr/openent/formulaire/controllers/FormElementController.java
Fix drag and drop in reorganization pop-up.
When saving we got sections, questions and questions inside sections. These last questions have all null positions, making the checking fail in back checking. So we filter these for ou check which is only about the main form elements.
FOR-607 : https://jira.support-ent.fr/browse/FOR-607
=> fix(orga-popup): [#FOR-607] fix drag and drop in reorganization pop-up

formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts
When responding to a form a section would send you to the the following element instead of the targeting one if existing. Now it does.
FOr-627 : https://jira.support-ent.fr/browse/FOR-627
=> fix(targeting): [#FOR-627] fix section targeting

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
When responding to a form in the preview, a section would send you to the the following element instead of the targeting one if existing. Now it does.
FOR-627 : https://jira.support-ent.fr/browse/FOR-627
=> fix(targeting): [#FOR-627] fix section targeting in preview

formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFormServiceTest.java
When a form was shared with a user (with manager rights), he could not export the form.
This bug was due to a wrong right parameter passed in the the checkFormsRights method of the formService.
The right passed was MANAGER_RESOURCE_RIGHT instead of MANAGER_RESOURCE_BEHAVIOUR and the pgsql query could not find anything, so we got a 401 error.
https://jira.support-ent.fr/browse/FOR-625
=> fix(export): #FOR-625 change right reference in checkFormsRight call for exporting

formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java
When exporting a form in pdf with conditional questions within a section, each question has now the title of the relative form element to which that question points.
Also the question choices are now in the right order on pdf.
Export a form with conditional questions whithin and without sections.
[FOR-628](https://jira.support-ent.fr/browse/FOR-628)
=> fix(exportPDF): #FOR-628 handle display of next titles for conditional questions when exporting

formulaire/src/main/resources/public/template/containers/edit-form.html, formulaire/src/main/resources/public/ts/directives/question/question-item/question-item.directive.ts, formulaire/src/main/resources/public/ts/directives/question/question-item/question-item.html, formulaire/src/main/resources/public/ts/directives/question/question-type.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-freetext.ts, formulaire/src/main/resources/public/ts/directives/section-item/section-item.directive.ts, formulaire/src/main/resources/public/ts/directives/section-item/section-item.html
*When sharing a public form, the responder can't access directly to the emitter's workspace to load the pictures.*
*These public pictures must be stored in a separate folder called "pub". To do that, we have to add the "visibility" property to the "editor" tag (which represents the WISIWYG editor).*
e.g : `<editor ng-model="vm.question.statement" visiblity="vm.form.is_public" input-guard></editor>`
*Visibility gets form's "is_public" property and set its value to 'public' if true or empty if false.*
*To pass this boolean value to the directive, the object "form" has been passed from every question type to its children.*
*Create a public form and add a picture in question text area.*
*Also try by adding a section and put a picture in the description.*
*When openeing the form link in your …
=> fix(public): #FOR-563 display pictures in public form response

formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer/question-type-singleanswer.html
Remove a closing div tag which prevented the select tag from being inside a ng-repeat, so the conditional questions were not displayed in the right way.
Make a form with contitional questions to check whether each question has an input to choose the next question destination.
[FOR-686](https://jira.support-ent.fr/browse/FOR-686)
=> fix(conditional): #FOR-686 fix regress of displaying conditional questions

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
When opening the lightbox to create a new form element, an autosaving of the form elements is triggered behind.
The problem was when clicking to validate the creation of the new element and closing the lightbox this background task was not over, resulting in partial or false values calculated for the new element.
Thus the new element was badly positionned and impossible to save afterward.
FOR-663 : https://jira.support-ent.fr/browse/FOR-663
FOR-638 : https://jira.support-ent.fr/browse/FOR-638
=> fix(new-element): [#FOR-663] fix element created in position 2 instead of at the end of the form

formulaire/src/main/resources/public/template/containers/tree-view.html, formulaire/src/main/resources/public/ts/controllers/form-tree-view.ts
To populate the svg in DOM, the dagre-D3 librarie needs to target the right svg. But in ng2, a svg was added in the header so the librairie took this svg and the tree graph generation didn't work anymore. So an id was added to the right svg in order to target it and populate it in the controller.
Go to ng2 with for example suzie die and choose a form. Than double click on it to go to the form edit page. Then click on "visualiser le parcours".
[FOR-687](https://jira.support-ent.fr/browse/FOR-687)
=> fix(formTreeView): #FOR-687 add id to svg in html to target tag with more accuracy

common/src/main/resources/ts/models/FormElement/FormElement.ts, common/src/main/resources/ts/models/FormElement/FormElements.ts, common/src/main/resources/ts/services/FormElement/QuestionService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java, formulaire/src/main/resources/public/template/containers/edit-form.html, formulaire/src/main/resources/public/template/lightbox/new-element.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
We optimized the syncing of a form (or rather a list of form elements) by doing only 4 API calls. So it's now independant of the number of elements, choices, etc. Then we simply, map our objects to link everything (sections, questions, choices, etc.)
These API calls are :
- get all sections
- get all questions (including the ones inside sections)
- get all choices for these questions
- get all children for these questions (children are lines of a question matrix)
Thanks to this we were able to revert a temporary fix made here : https://github.com/OPEN-ENT-NG/form/pull/304
FOR-689 : https://jira.support-ent.fr/browse/FOR-689
=> refacto(sync): [#FOR-689] form-editor optimization on syncing

common/src/main/resources/ts/directives/progress-bar.ts, formulaire/src/main/resources/public/template/containers/respond-question.html, formulaire/src/main/resources/public/ts/controllers/respond-question.ts
Now the progress bar takes the longest path each time the user is answering a question. As the form can have some conditional question leading to other parts of the form, the new method calculates the longest path regarding the conditional choices and the different possibilities of user's answers.
Open a form with a user whom the form has been shared.
Answer the questions and the progress bar must adapt to your choices.
If you want to check whether the path is correct, open the edit page of the form whith the user who has created it and count the max number of form elements we can answer. You can use the new tree for view to be more confortable.
[FOR-590](https://jira.support-ent.fr/browse/FOR-590)
=> fix(progressBar): #FOR-590 change method of progress bar rendering when answering a form

common/src/main/resources/ts/utils/formElement.ts
On some specific cases when using drag and drop we were losing the scope of the dragged element.
This scope was needed to get the element's id and thanks to the id to get the object itself.
To fix this we used another way to get this object via the original index and the original container.
- Create a form with one section and two questions
- Add two questions inside the section
- Open the organization lightbox
- Take the last element of the form (the second question) and put it in the section
- Take another element inside the section and put it outside
- When bugging, the CSS shift before the element was still large as if the element was in the section instead of being aligned with the other form elements. Now, it should behave correctly.
FOR-639 : …
=> fix(DnD): [#FOR-639] fix drag and drop in organization lightbox

formulaire/src/main/resources/public/ts/controllers/forms-list.ts
When we exported a form as PDF and then open again the lightbox, the selected value was PDF instead of being the default one (ZIP)
- Export a form as PDF
- Open again the lightbox for export
- The sleected choice should be the default one (ZIP)
FOR-674 : https://jira.support-ent.fr/browse/FOR-674
=> fix(export): [#FOR-674] fix default value for export

common/src/main/java/fr/openent/form/core/enums/I18nKeys.java, common/src/main/java/fr/openent/form/helpers/I18nHelper.java, formulaire/src/main/java/fr/openent/formulaire/controllers/SharingController.java, formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/template/lightbox/form-sharing.html, formulaire/src/main/resources/public/ts/controllers/forms-list.ts
We add a custom message in back sharing controller to send it back to the directive.
As this directive **(share-panel)** is in infra-front, we handled a new case in that directive by passing the error in a new function in the catch section like this :
**$attributes.onFailure ? $scope.onFailure( {'$error' : e} ) : notify.error('share.notify.error');**
Then, we passed this function onFailure directly to the html tag of the directive to get the error back in our module and send a **notify.error** with it.
Check the infra-front PR for more information :
https://github.com/CGI-OPEN-ENT-NG/infra-front/pull/8
In ent-core.json, set the "max-users-sharing" to 0 (in formulaire config), then try to share a form to someone. A warning must appear.
[FOR-516](https://jira.support-ent.fr/browse/FOR-516)
=> fix(share): #FOR-516 inform the user that he can't share his form because the users sharing configuration has been exceeded

common/src/main/java/fr/openent/form/core/constants/ShareRights.java, common/src/main/java/fr/openent/form/core/models/ShareObject.java, common/src/main/java/fr/openent/form/helpers/RightsHelper.java, formulaire/src/main/java/fr/openent/formulaire/controllers/DistributionController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/FormElementController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionChoiceController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/ResponseFileController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/SectionController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/SharingController.java, formulaire/src/main/java/fr/openent/formulaire/security/CustomShareAndOwner.java, formulaire/src/main/resources/public/ts/behaviours.ts, formulaire/src/main/resources/sql/027-add-sharing-rights.sql
We improved API security. Before, some API routes were secured by an AccessRight.class file only checking if the connected user had a workflow right to access the Formulaire mod.
That means anyone acessing Formulaire could call these API and get the responses.
We changed that by using the sharing security system : now, you need to have at least one sharing right on the form to call these API and get the infos.
To sum up :
- Before if acessing Formulaire you could get many infos of forms not related to you at all
- Now you need these forms to be shared to you as contributor, manager or responder at least to get these infos
All the refacto/improvement/modeling will be in the following ticket : https://jira.support-ent.fr/browse/FOR-692
FOR-636 : https://jira.support-ent.fr/browse/FOR-636
=> fix(sharing): [#FOR-636] improve sharing rights system

common/src/main/java/fr/openent/form/core/enums/I18nKeys.java, common/src/main/resources/ts/services/FormService.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/export/FormQuestionsExportPDF.java, formulaire/src/main/java/fr/openent/formulaire/helpers/folder_exporter/FolderExporterZip.java, formulaire/src/main/java/fr/openent/formulaire/service/FormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/template/lightbox/form-export.html, formulaire/src/main/resources/public/ts/controllers/forms-list.ts, formulaire/src/test/java/fr/openent/formulaire/service/test/impl/DefaultFormServiceTest.java
Allow to export several forms PDF files at the same time.
In order to do that, for each form we create the PDF and store it in the storage. Than we create a ZIP with all of them and download it.
In case there is only one form we don't create a ZIP, we just download the PDF directly.
We also separated API routes for ZIP export and PDF export.
Documentation updated : https://confluence.support-ent.fr/display/FOR/Form#Form-export
FOR-680 : https://jira.support-ent.fr/browse/FOR-680
=> fix(export): [#FOR-680] allow to export several forms at PDF format

formulaire/src/main/resources/public/sass/index.scss
There was a bad height of navbar because of general import of all entcore-css-lib files.
Indeed, it forced the navbar class to have a height of 40px.
By removing this general import and keep only the file we need to import, we get rid of this behaviour.
[FOR-708](https://jira.support-ent.fr/browse/FOR-708)
=>  fix(css): #FOR-708 change entcore-css-lib import and keep only variable file

formulaire/src/main/resources/public/sass/global/components/_prop-form.scss, formulaire/src/main/resources/public/template/containers/prop-form.html
On the Property view of a form, the area for adding an image was stretch and it was ugly.
We fiwed it to keep the proportions of the image.
FOR-567 : https://jira.support-ent.fr/browse/FOR-567
=> fix(image): [#FOR-567] fix image proportions in form prop view

common/src/main/resources/ts/core/constants/fields.ts, common/src/main/resources/ts/models/Form.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/EventBusController.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionChoiceService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionService.java
- EventBus messages don't like modeled data. Here we had a JsonArray but full of Question object. To make the EventBus reply work we needed to convert those models to simple JsonObject and JsonArray.
- We also fixed the front data fetching and converting for cursor questions
FOR-716 : https://jira.support-ent.fr/browse/FOR-716
=> fix(public): [#FOR-716] fix formulaire public response

formulaire/src/main/resources/public/ts/controllers/form-editor.ts
In a matrix form element, when you want to delete a question choice (matrix column), you can click on the cross corresponding to the input.
Now if you remove the string value of the input, the question choice will also be delated when updating.
This change fits the behaviour of matrix children (lines).
Edit an existing form with matrix columns.
Remove existing value of a column and click outside of the matrix form element.
[FOR-715](https://jira.support-ent.fr/browse/FOR-715)
=> fix(update): #FOR-715 delete empty matrix questionChoice when updating

formulaire-public/src/main/resources/public/template/containers/respond-question.html, formulaire-public/src/main/resources/public/template/lightbox/responses-confirm-sending.html, formulaire-public/src/main/resources/public/ts/controllers/captcha.ts, formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/template/components/toasters/toaster-forms-list.html, formulaire/src/main/resources/public/template/containers/edit-form.html, formulaire/src/main/resources/public/template/containers/prop-form.html, formulaire/src/main/resources/public/template/containers/respond-question.html, formulaire/src/main/resources/public/template/containers/results-form.html, formulaire/src/main/resources/public/template/lightbox/form-confirm-archive.html, formulaire/src/main/resources/public/template/lightbox/form-export.html, formulaire/src/main/resources/public/template/lightbox/questions-reorganization.html, formulaire/src/main/resources/public/template/lightbox/responses-confirm-sending.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/controllers/form-prop.ts, formulaire/src/main/resources/public/ts/controllers/forms-list.ts, formulaire/src/main/resources/public/ts/controllers/recap-questions.ts, formulaire/src/main/resources/public/ts/controllers/respond-question.ts
Added ng-disable to prevent certain buttons spamming and consequences
Here is the list of impacted's buttons : 
edit-form : saveAll
prop-form : saveGuard
toaster-forms-list : duplicateForm 
forms-list : doExportForms 
forms-list : doArchiveForms 
respond-question : next 
recap-question : doSend  
captcha : doSend 
[FOR-595](https://jira.support-ent.fr/browse/FOR-595)
=> fix(buttons): #FOR-595 block user from spamming buttons

formulaire/src/main/resources/public/ts/controllers/recap-questions.ts
This ticket deals with a responder wanting to change the files in a question of type file.
When modifying his response, he had an error concerning the deletion of the former file(s).
In order to clean storage, there was an instruction to remove all the files of a specific response when updating it (if we change the files). But actually, this instruction is already called when updating files in the saveFiles function :
**await responseFileService.deleteAll(response.id);**
As the former file was already removed from the storage, it could not find the file afterward and so could not remove it again.
We simply removed this instruction in the code.
Create a form with a question of type file. Then share it to someone. Then answer to the form (when logged as the responder) by uploading a file, …
=> fix(doSend): #FOR-713 remove deleteAll files instruction when sending  response

formulaire/src/main/resources/public/ts/directives/question/recap-question-item/recap-question-item.html
When refactoring the racp-item directive we whange the name of a variable but forgot an occurence in HTML code, creating a bug.
Now the HTML calls the right variable name.
FOR-302 : https://jira.support-ent.fr/browse/FOR-302
=> fix(recap): [#FOR-302] hide "Modify" buttons when form is not editable

common/src/main/java/fr/openent/form/core/constants/Fields.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/FormulaireRepositoryEvents.java
We now update the ids of images when importing a form to avoid any display issue.
Indeed, before that, every image imported kept the former id of image exported in the original form which was confusing and led to non valid image paths.
Import a form with QCM images several times to make sure images are well displayed.
[FOR-698](https://jira.support-ent.fr/browse/FOR-698)
=> fix(zip): #FOR-698 handle display of images in imported form

formulaire/src/main/resources/public/ts/directives/question/question-type.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer/question-type-singleanswer.html
- We added a missing prop to allow images in singleanswerradio question for public forms
- In editor view, we block the possibility to put images in question choices. Indeed, we don't display images in response view so there no use to be able to add them here.
FOR-727 : https://jira.support-ent.fr/browse/FOR-727
=> fix(singleanswer): [#FOR-727] fix some image behviors

common/src/main/resources/ts/models/QuestionChoice.ts, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
The duplication of a question with the custom choice now works well.
The problem was the choice was duplicated but not with the is_custom prop set to true.
FOR-726 : https://jira.support-ent.fr/browse/FOR-726
=> fix(choice): [#FOR-726] fix choice duplication

formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java
When a form is restored, we have to update it in dataBase and the ending date of the form was typed as a date instead of a string so we add an internal error.
Create a public form, delete it restore it through the files trash.
[FOR-753](https://jira.support-ent.fr/browse/FOR-753)
=> fix(restore): #FOR-753 cast dateEnding to string when uptade

formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-matrix/question-type-matrix.html
In matrix questions, the down chevron was missing, so we could no longer rearrange the choices.
Create a matrix question, single or multiple choice, when you add some choice, you should be able to move it down and up
[FOR-765](https://jira.support-ent.fr/browse/FOR-765)
=> fix(question-type-matrix): #FOR-765 add missing icon chevron down

common/src/main/resources/ts/services/QuestionChoiceService.ts, common/src/main/resources/ts/utils/formElement.ts, formulaire/src/main/java/fr/openent/formulaire/controllers/FormElementController.java, formulaire/src/main/java/fr/openent/formulaire/controllers/QuestionChoiceController.java, formulaire/src/main/java/fr/openent/formulaire/security/CustomShareAndOwner.java, formulaire/src/main/java/fr/openent/formulaire/service/QuestionChoiceService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultQuestionChoiceService.java, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/question/question-type/question-type-singleanswer/question-type-singleanswer.directive.ts, formulaire/src/main/resources/sql/028-add-sharing-rights.sql
We now save all choices from conditional questions after DnD.
It allows to save potential target changes generated by positions changing.
Documentation API : https://confluence.support-ent.fr/display/FOR/Question+Choice#operations-tag-default
FOR-782 : https://jira.support-ent.fr/browse/FOR-782
=> fix(conditional): [#FOR-782] fix choice targeting on elements reorganization

common/src/main/resources/ts/services/FormElement/QuestionService.ts, common/src/main/resources/ts/services/FormElement/SectionService.ts, common/src/main/resources/ts/services/FormService.ts, common/src/main/resources/ts/services/QuestionChoiceService.ts, common/src/main/resources/ts/services/ResponseService.ts
When calling some enpoints we use some lists as params. When the list is empty we now immediately return an empty list.
- Create a form
- Create some questions without any choices
- Reorganize elements with the dedicated pop up
- When saving it was displaying an error that should not exist anymore
FOR-804 : https://jira.support-ent.fr/browse/FOR-804
=> fix(reorganization): [#FOR-804] fix front services when params are empty

formulaire/src/main/resources/public/template/lightbox/new-element.html, formulaire/src/main/resources/public/ts/controllers/form-editor.ts
We add a loader to a pop up to wait that all the form elements are saved before displaying anything
FOR-807 : https://jira.support-ent.fr/browse/FOR-807
=> fix(progress-bar): [#FOR-807] wait elements saving before displaying pop up for a new one

common/src/main/resources/ts/directives/progress-bar.ts, common/src/main/resources/ts/models/FormElement/FormElement.ts, common/src/main/resources/ts/utils/formElement.ts, formulaire-public/src/main/resources/public/template/containers/recap.html, formulaire-public/src/main/resources/public/template/containers/respond-question.html, formulaire-public/src/main/resources/public/ts/controllers/respond-question.ts, formulaire/src/main/resources/public/template/containers/edit-form.html, formulaire/src/main/resources/public/template/containers/preview-form.html, formulaire/src/main/resources/public/template/containers/recap-questions.html, formulaire/src/main/resources/public/template/containers/respond-question.html, formulaire/src/main/resources/public/template/containers/results-form.html, formulaire/src/main/resources/public/template/lightbox/questions-reorganization.html, formulaire/src/main/resources/public/ts/controllers/respond-question.ts
The progress-bar shows to the user the number of questions already answered and the number remaining if continuing this flow of responses.
Before, these numbers were calculated at each page of response, according the selected flow.
But these flow are fixed from the begining so now we do all the calculation, store them in a map and simply get the corresponding value when navigating between pages.
FOR-808 : https://jira.support-ent.fr/browse/FOR-808
=> refacto(progress-bar): [#FOR-808] improve calculations for progress-bar display

common/src/main/resources/ts/utils/formElement.ts, formulaire/src/main/resources/i18n/en.json, formulaire/src/main/resources/i18n/fr.json, formulaire/src/main/resources/public/ts/controllers/form-editor.ts, formulaire/src/main/resources/public/ts/directives/section-item/section-item.directive.ts, formulaire/src/main/resources/public/ts/directives/section-item/section-item.html
When saving form elements on drag and drop (form editor view or reorgnaization pop up) we now do some more checks to avoid cases like two conditionnal in a section or things like that
FOR-810 : https://jira.support-ent.fr/browse/FOR-810
=> fix(reorganization): [#FOR-810] add checks before saving when drag and drop elements

common/src/main/resources/ts/core/constants/constants.ts, common/src/main/resources/ts/utils/graph.ts, formulaire/src/main/resources/public/ts/directives/question/result-question-item/result-question-item.directive.ts
Graph colors where previously generated semi-randomly every time a graph was displayed.
Now our 25 colors are ordered in a specific order and graphs always use these colors in these specific order.
FOR-549 : https://jira.support-ent.fr/browse/FOR-549
=> feat(colors): [#FOR-549] make graph colors constant

common/src/main/java/fr/openent/form/core/constants/Fields.java, common/src/main/java/fr/openent/form/core/models/Form.java
toJson() function in Form model, was causing cast error because of a stringyfied enum. We add to reset the right value accordingly.
FOR-829 : https://jira.support-ent.fr/browse/FOR-829
=> fix(model): [#FOR-829] fix form.toJson()

formulaire/src/main/java/fr/openent/formulaire/controllers/FormController.java, formulaire/src/main/java/fr/openent/formulaire/service/FormService.java, formulaire/src/main/java/fr/openent/formulaire/service/impl/DefaultFormService.java, gradle.properties
Pour que le front puisse recalculer correctement l'heure à afficher selon la timezone côté client, le back doit fournir les dates des formulaires (création, modification) avec les informations de timezone.
Ces informations sont bien persistées en base dans le cas des formulaire, mais l'information est perdue lorsque l'on récupère l'information depuis la base de donnée.
Étant donnés les risques liés au fait de corriger le problème côté mod-postgres (car transverse à toutes les applications utilisant une base Postgres), la solution implémentée consiste à redonner les informations de Timezone du serveur tronquées par mod-postgres, côté application gestionnaire de ressource.
Le cadrage technique est détaillé [ici](https://edifice-community.atlassian.net/wiki/spaces/ODE/pages/3777626144/Gestion …
=> fix: WB-2579, enrich form dates with timezone offset

formulaire/frontend/src/containers/FolderModal/index.tsx
This pull request includes a small change to the `FolderModal` component in the `formulaire/frontend/src/containers/FolderModal/index.tsx` file. The placeholder text for the `TextField` has been removed.
* [`formulaire/frontend/src/containers/FolderModal/index.tsx`](diffhunk://#diff-0e2c3ea69ce7d755c6874df601d7a143b17878b85f7db4a7a4a908a59cc1ef81L100): Removed the placeholder text from the `TextField` component
=> fix(placeholder): #FOR-886 remove placeholder from folder modal

formulaire/frontend/src/containers/HomeMainFormsTable/utils.ts, formulaire/frontend/src/containers/HomeMainSentFormTable/index.tsx, formulaire/frontend/src/containers/HomeMainSentFormTable/utils.ts, formulaire/frontend/src/core/models/form/utils.ts, formulaire/frontend/src/hook/useFolderSubtitle.ts, formulaire/frontend/src/hook/useFormItemsIcons.tsx, formulaire/frontend/src/hook/useFormatDateWithTime.ts, formulaire/frontend/src/i18n.ts, formulaire/frontend/src/providers/HomeProvider/utils.ts, formulaire/frontend/src/services/api/services/archiveApi/importExportApi.ts, formulaire/frontend/src/services/api/services/formulaireApi/distributionApi.ts, formulaire/frontend/src/services/api/services/formulaireApi/folderApi.ts, formulaire/frontend/src/services/api/services/formulaireApi/formApi.ts
* **Core change:**
All calls to translations now use a direct `import i18n` + `i18n.t()` instead of the `useTranslation` hook and passing around `t`.
* **What was removed:**
* The `useTranslation` hook
* `t` parameters in utility functions and components
* **Where it applies:**
* **Hooks:** `useColumns`, `useFolderSubtitle`, `useFormatDateWithTime`, `useFormItemsIcons`
* **Utilities:** `getFormStatusText`, column‐building helpers
* **Components:** Main and Sent Forms tables
* **Why it matters:**
* Eliminates boilerplate
* Keeps translation logic consistent
* Simplifies the codebase
=> refactor(i18n): refactor i18n in hooks

formulaire/frontend/src/containers/HomeMainFormsTable/index.tsx
This pull request introduces enhancements to the `HomeMainFormsTable` component in the `formulaire` frontend, focusing on pagination logic and improving the user interface for displaying form titles. 
- addition of a `useEffect` hook to handle deletion of a form when its the last in its page 
- use of a tooltip for truncated form titles
[FOR-883](https://jira.support-ent.fr/browse/FOR-883)
=> fix(return): #FOR-883 fix css and page in the table

formulaire/frontend/src/containers/MoveFolderModal/index.tsx, formulaire/frontend/src/containers/MoveFolderModal/utils.ts
This pull request enhances the functionality of the `MoveFolderModal` component by allowing the exclusion of specific folders from the folder tree view. The changes optimize the folder tree-building process and improve performance by using a `Set` for efficient lookups. 
* Modified the `treeViewItems` initialization in the `MoveFolderModal` component to pass the `selectedFolders` as the `foldersToExcludeList` parameter to the `buildFolderTree` function. (`formulaire/frontend/src/containers/MoveFolderModal/index.tsx`, [formulaire/frontend/src/containers/MoveFolderModal/index.tsxL32-R32](diffhunk://#diff-e3fb32bfefb9f8574b144162c2588dcda73c8c4d3e484a11a245d791d4a3f26aL32-R32))
[FOR-978](https://jira.support-ent.fr/browse/FOR-978)
=> fix(folder): #FOR-978 fix moving folder into itself

formulaire/src/main/java/fr/openent/formulaire/helpers/upload_file/FileHelper.java
Modification de la méthode d'upload des graphs (front > back > export).
Une partie du code était codé en dur au lieu de passer par la classe Storage, entraînant une régression lors de l'utilisation d'ObjectStorage.
[#COCO-4312](https://edifice-community.atlassian.net/browse/COCO-4312)
=> Fix coco 4312 download results in pdf format
